### ISSUE TITLE
[Android] Game speeds up when the phone display is set past 60hz

### ISSUE THREAD

**Issue by ActualMandM** [Rubberduckycooly/RSDKv5-Decompilation#1]
**Describe the issue**
When running the decomp on a phone that has it's refresh rate set to anything higher than 60hz, the game will be sped up to the display's refresh rate instead of capping to 60 fps.

**To Reproduce**
1. Make sure phone's refresh rate is set anywhere past 60 (some phones do 90, others do 120)
2. Boot RSDKv5 up

**Expected behavior**
The game should be running at 60 fps despite the phone's display refresh rate.

**Device Details:**
 - Phone: Samsung Galaxy S22+
 - OS: Android 12
 - Version: 1.0.0
 
 **Log:**
 https://cdn.discordapp.com/attachments/563003189046018072/1008932666365726751/log.txt

**Comment by MisterSheeple** [comment]
As a temporary workaround, you can set your device into power saving mode, which will force it to display at 60 Hz.

**Comment by MGRich** [comment]
Should be fixed for good ever since 98a7fa03d6698972e80add57c6dcb9cc0983628a.
