### ISSUE TITLE
(Linux) make: *** No rule to make target 'bin/obj/Linux/GL3/RSDKv5/dependencies/all/tinyxml2/tinyxml2.o', needed by 'bin/Linux/GL3/RSDKv5'.  Stop.

### ISSUE THREAD

**Issue by MavisCelus19201** [Rubberduckycooly/RSDKv5-Decompilation#10]
I get this error when I try to compile this after running make

"make: *** No rule to make target 'bin/obj/Linux/GL3/RSDKv5/dependencies/all/tinyxml2/tinyxml2.o', needed by 'bin/Linux/GL3/RSDKv5'.  Stop."

I have tinyxml2 installed already so I don't know what's up with that. I had a similar error where it needed stb_vorbis.c to compile audio, which wasn't in the build folder either but copying it from my own install of that worked.

**Comment by santiagocezar** [comment]
You probably forgot to run `git submodule update --init`, it says in [this README](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/master/dependencies/all/README.md) that those 2 are submodules (and I have missed it too, lol)

That text should probably be directly included in the project's README, it's pretty short anyways

**Comment by MGRich** [comment]
You can also add `--recurse-submodules` when you initially clone it,
