### ISSUE TITLE
[Fedora Linux] Is libtheora-devel required?

### ISSUE THREAD

**Issue by Shoptalky** [Rubberduckycooly/RSDKv5-Decompilation#102]
When attempting to make on fedora linux without libtheora-devel installed, I got this error message. Installing that made it compile normally.

```
Package theora was not found in the pkg-config search path.
Perhaps you should add the directory containing `theora.pc'
to the PKG_CONFIG_PATH environment variable
Package 'theora', required by 'virtual:world', not found
Package 'theoradec', required by 'virtual:world', not found
In file included from RSDKv5/main.cpp:1:
RSDKv5/RSDK/Core/RetroEngine.hpp:466:10: fatal error: theora/theoradec.h: No such file or directory
  466 | #include <theora/theoradec.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:224: bin/obj/Linux/GL3/RSDKv5/RSDKv5/main.o] Error 1

```

I was confused because this wasn't listed with the other required dependencies. It might seem like an obvious thing to install once you get the error, but to minimise inconvenience and for completeness I think it should be listed if it is required

**Comment by MGRich** [comment]
Yes. 9cc8854d448ce1e807986b5984c91511fc3e9684
