### ISSUE TITLE
[DX9/DX11] Button mapped to shift, ctrl or alt is always registered as held down once it's pressed on keyboard

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#107]
If you're using a keyboard on the DX9 or DX11 versions of the decomp, once you press a button that's mapped to shift, ctrl, or alt (either left or right), it's always registered as held down, regardless of if you're physically pressing it. This doesn't happen on GL3 or SDL2, nor does this happen in the Steam version of Mania.

**Comment by Rubberduckycooly** [comment]
should be fixed in 93d7c59f55e63f179a6d8941965f048e307ffa8b
