### ISSUE TITLE
ExcludeFile and ExcludeAllFiles do nothing

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#109]
I tested excluding these files through config options and it still used the custom files even if the options were disabled.
Here's the code I used to test this (in InitModAPI). I also tried using ExcludeAllFiles and that didn't work either.
![image](https://user-images.githubusercontent.com/7158344/193468258-03a2ae78-13a0-4830-8ad2-afcdb0cc17d7.png)
For modID I tried both ``modID`` and directly using the folder name, but that didn't change anything.
EDIT: Found out you're supposed to use ``""`` for the modID to specify the current mod, but that still didn't work.

**Comment by Rubberduckycooly** [comment]
should be fixed in c9697ed88b1c597c2e3946198b93d13c9a06dee2, reopen this and ping me if it isn't.

**Comment by MegAmi24** [comment]
Can confirm it works now, thanks
