### ISSUE TITLE
[Linux/Switch] Glitched FMVs using OpenGL shaders

### ISSUE THREAD

**Issue by icup321** [Rubberduckycooly/RSDKv5-Decompilation#112]
I compiled Sonic Mania for both Switch and Linux from the latest commits and have properly set them up to load GL3 Shaders, but for whatever reason the FMVs don't render properly on both platforms: 
![Screenshot_from_2022-09-07_03-35-01](https://user-images.githubusercontent.com/28464642/194218384-14e8f844-3d9e-44f2-a11f-25cc8d443d2c.png)
I have tried several methods to fix this, including running both RSDKv5 and RSDKv5U executables, using older commits, updating and reinstalling graphics drivers, but nothing seems to work so I'm going to assume the OpenGL shaders are bugged. Here's the log: 
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9721377/log.txt)

**Comment by LittlePlanetCD** [comment]
shaders work fine for me on the FMVs on switch.

**Comment by santiagocezar** [comment]
Are you on the latest commit? Pretty sure this just got fixed in https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/ca775a2a6c4cf4f0b0be62104e12ad41ac527bae

**Comment by icup321** [comment]
> ~Are you on the latest commit? Pretty sure this just got fixed in~ [ca775a2](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/ca775a2a6c4cf4f0b0be62104e12ad41ac527bae)
> 
> My bad didn't read that you actually you were on latest, but again, I was able to reproduce the issue recently, brought it up and then it got fixed by that commit.
> 
> Make sure you have copied the newest shaders to your mod folder.

Yeah that was it, I could've sworn I thought I had copied the newest ones over, but I guess I just used the older Shaders instead thinking they were the same, *sigh*...
