### ISSUE TITLE
[RSDKv5U] Legacy v3/v4 mod Game.xml files with stages crash the game

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#119]
I've tried loading two mods that use Game.xml files, one for S2/v4 and one for CD/v3, making sure both of them have the TargetVersion tag, however both mods crash after loading the file. These mods load properly in the standalone decomps, so this is only affecting v5U. I've tested other mods that don't have a Game.xml file and they work fine, and Game.xml files for Mania/v5 also work.

**Comment by MegAmi24** [comment]
After some testing, the game only crashes if the Game.xml file has any stages in it.

**Comment by Rubberduckycooly** [comment]
fixed in c3cce1595550648ec0694a92095d47f7ef501f73
