### ISSUE TITLE
Can't use DLC on RK3326 devices (Portmaster)

### ISSUE THREAD

**Issue by thalyy36** [Rubberduckycooly/RSDKv5-Decompilation#121]
Always boots to base game even though I have the Sonic Mania Plus dlc installed.

**Comment by MegAmi24** [comment]
You need to build the decomp yourself for the DLC

**Comment by MegAmi24** [comment]
You need to build the decomp yourself for the DLC

**Comment by thalyy36** [comment]
> You need to build the decomp yourself for the DLC

I followed this tutorial right here, on PC it showed up but, on my GameForce Chi, it didn't, still says it could not locate the DLC.

**Comment by MegAmi24** [comment]
The decomp doesn't look for whether or not you have the DLC installed on any official release of Mania, so whatever issue you're having isn't the decomp's fault.

**Comment by thalyy36** [comment]
![Screenshot_20221025_235808](https://user-images.githubusercontent.com/44348544/197924658-206f3740-32df-4347-ac09-a31963f0d1ef.png)
I have found the issue, I don't know how to do this but, I will be trying.
