### ISSUE TITLE
GL3 builds don't have window or taskbar icons

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#122]
Backend order from left to right is DX9, DX11, GL3, and SDL2
v5 on top, v5U on bottom
![image](https://user-images.githubusercontent.com/7158344/198729427-6faab290-db12-4e88-9eae-8c278005d829.png)

Same backend order here, the first four are v5 and the second four are v5U
![image](https://user-images.githubusercontent.com/7158344/198729656-013a0e9d-636c-4669-a183-6ae72806ac36.png)

They all have icons in File Explorer though
![image](https://user-images.githubusercontent.com/7158344/198729847-8dc98105-8ce3-453d-b634-74d8c745630b.png)

**Comment by MGRich** [comment]
Due to how resources work, GLFW is likely not seeing it. Will mess with it to see if I can get it to show up.
