### ISSUE TITLE
[GL] Game game launches in small rectangle.

### ISSUE THREAD

**Issue by 6ell** [Rubberduckycooly/RSDKv5-Decompilation#126]
![Снимок экрана (161)](https://user-images.githubusercontent.com/118050160/201469870-9e633be6-1e96-4e61-9676-035600f2086f.png)
On RSDKv5-gl3_64.exe

**Comment by MGRich** [comment]
What's your GPU and its OpenGL version?

**Comment by 6ell** [comment]
> What's your GPU and its OpenGL version?

Integrated AMD Radeon Vega 8. OpenGL version is 4.6

**Comment by 6ell** [comment]
![изображение](https://user-images.githubusercontent.com/118050160/201980653-3a9a3e5e-19cd-4517-ab2a-986d130a387d.png)
Now it's just a white rectangle. No game, no music.

**Comment by MGRich** [comment]
That means that game logic didn't link which is due to your setup, but clearly small screen wasn't fixed by this commit unfortunately.. This is the first case of this bug I've seen on Window, which makes it very valuable to debug. @Mefiresu has stated that it's likely an AMD GL driver issue, but please hold off on updating it if at all possible. I'll try other fixes in a bit and will get back to you periodically to see if Android can be fixed as well.

**Comment by MGRich** [comment]
Actually, let's try this too:

Download RenderDoc from https://renderdoc.org/.
Go to the Launch Application tab (might need to be opened from Window) and set it to launch the `RSDKv5-gl3` executable.
Queue 5 captures from the first frame as so:
![image](https://user-images.githubusercontent.com/29069561/201987856-4fdfc61b-2657-4dce-bbde-2768968c3677.png)
Upload them and send them here.

**Comment by 6ell** [comment]
AMD GPU driver version is 30.0.13023.4001.

**Comment by MGRich** [comment]
These captures show pre-ba8c62b behavior. Pull/rebuild and capture again.
![image](https://user-images.githubusercontent.com/29069561/202211198-700f9b38-c74b-4f4d-b672-db0c2bedb381.png)

**Comment by 6ell** [comment]
[FrameCaps2.zip](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/10023048/FrameCaps2.zip)

**Comment by MGRich** [comment]
Is this producing the same output for the white rectangle/small screen?

**Comment by 6ell** [comment]
[triedtosetshadersup.zip](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/10031167/triedtosetshadersup.zip)

**Comment by 6ell** [comment]
[RSDKv5U-OGL.zip](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/10031250/RSDKv5U-OGL.zip)
Tried to rebuild again.

**Comment by MGRich** [comment]
Shaders mod still doesn't appear to be on (missing `pixelSize`, `viewSize`, and `textureSize` uniforms.) Make sure you have a mod with the data structure of `Data/Shaders/OGL/None.vs`.

For now, what resolution are you running v5 on? Is it fullscreen or windowed?

**Comment by 6ell** [comment]
Fullscreen 1366x768 resolution.
Tried to set shaders up again. Now as you said.
[triedagain.zip](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/10033282/triedagain.zip)

**Comment by MGRich** [comment]
Do you have a custom `maxPixWidth` set in your Settings.ini? This is stating your pixWidth is 428, when by default it gets restricted to 424.

**Comment by MGRich** [comment]
Does this commit fix it all?

**Comment by 6ell** [comment]
Yes. It's all fine now.
Thank you.
I don't know about shaders, though.
