### ISSUE TITLE
Just a random question.

### ISSUE THREAD

**Issue by Earth9966zcx** [Rubberduckycooly/RSDKv5-Decompilation#128]
So uhhhh

Is it possible to make dll mods playable on android?, Im just kinda curious it cant or its not implemented yet.

**Comment by Kiaru-the-Fox** [comment]
DLL files are made specifically for Windows applications, and no other operating system can use them without a lot of workarounds. The only way to get a DLL mod to work on Android would be to put the mod's code into the vanilla game's code before compiling the APK.

**Comment by LittlePlanetCD** [comment]
yeah, kiaru is correct.

>The DLL extension file was developed by Microsoft and is popularly used by them. It has a high popularity user rating.

It's only ever used on Windows as far as i know, so there's no chance for the Android version of the decomp to use these due to Android not supporting it AND Android is a version of Linux.

**Comment by Earth9966zcx** [comment]
Thanks for the information :]
