### ISSUE TITLE
(Android) Black screen with sounds

### ISSUE THREAD

**Issue by LucasMegaStriker** [Rubberduckycooly/RSDKv5-Decompilation#13]
Trying to run on my Powkiddy X18S (Unisoc T618, Mali) and got black screen. Music seems to play just fine, and the controls too (built-in gamepad from the X18S). So, any fix for the black screen?

**Comment by LucasMegaStriker** [comment]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9354716/log.txt)
The log file mentions missing GL files.

**Comment by LucasMegaStriker** [comment]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9354722/log.txt)
The log file mentions missing GL files.

**Comment by SuperSonic40** [comment]
Is cuz you have Mediatek processor or something else

**Comment by LittlePlanetCD** [comment]
if this device of yours is an android that doesn't have a snapdragon processor, then the decomp will not work for you correctly.

This has been reported many times on different devices, so please wait for a fix when we can get to it.

**Comment by yehyasabry** [comment]
Me have mediatek CPU and I have black screen

**Comment by MGRich** [comment]
Duplicate of #8.
