### ISSUE TITLE
[Linux/RPi4] Building returns odd error

### ISSUE THREAD

**Issue by ghbbeep** [Rubberduckycooly/RSDKv5-Decompilation#130]
After successfully compiling all files, it spits out this:
linking RSDK...
/usr/bin/ld: cannot find -ldrm
/usr/bin/ld: cannot find -lgbm
collect2: error: ld returned 1 exit status
make: *** [Makefile:241: bin/Linux/SDL2/RSDKv5] Error 1

No idea how this happens. I believe I have all the dependencies installed.

**Comment by LittlePlanetCD** [comment]
Do you have libgbm and libdrm installed?

**Comment by ghbbeep** [comment]
I... don't know what those are. I'll check.

**Comment by LittlePlanetCD** [comment]
you can pull packages for libdrm-dev and libgbm-dev, should fix your problem.

**Comment by ghbbeep** [comment]
Seems to have worked. I'll update you if it did so we can close the issue.

**Comment by ghbbeep** [comment]
Yep! It worked! Thanks a bunch!
