### ISSUE TITLE
[Nintendo Switch] Current commits display black screen, even with shaders on.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#132]
How to do:

1. Build for Switch, set up all the files.

2. Launch NRO on console

3. black screen, even with shaders on or off.

My log shows that the game is loading these shaders, but it just doesn't display anything, even with them either on or off.

![image](https://user-images.githubusercontent.com/24783625/202593756-fba8cd98-7b8f-4a13-88a2-c7a4113f9670.png)

**Comment by MGRich** [comment]
Fixed in 77aa66081c1de73987cc3b699bd4796644c49ab1.
