### ISSUE TITLE
[HELP ME] I try to add the Shaders mod but nothing happens

### ISSUE THREAD

**Issue by h57758** [Rubberduckycooly/RSDKv5-Decompilation#138]
I tried to follow the Linux instruction, and it worked. But I couldn't get the Shaders to work. I have NOT installed the RSDK Mod Manager because the readme.md stated that it should be integrated.

**Comment by MegAmi24** [comment]
Did you enable the mod in the mod menu?

**Comment by h57758** [comment]
What mod menu?

**Comment by MegAmi24** [comment]
Enable the dev menu by adding ``devMenu=y`` in the Game category in settings.ini, then press escape in game, you should see a mods option, that's the mod menu

**Comment by h57758** [comment]
Now when I select Mods from the DevMenu it just simply shows nothing.

**Comment by h57758** [comment]
Screenshot of bin:
![Screenshot_2022-11-24_19-25-09](https://user-images.githubusercontent.com/63967786/203847716-90bdf37d-3336-4adf-b492-9fbda7609e49.png)

**Comment by MegAmi24** [comment]
you probably installed the mod wrong, show the mods folder

**Comment by h57758** [comment]
![Screenshot_2022-11-24_19-28-17](https://user-images.githubusercontent.com/63967786/203847930-18460281-6681-40df-9dc4-a95cd1ed951d.png)

**Comment by h57758** [comment]
> ![Screenshot_2022-11-24_19-28-17](https://user-images.githubusercontent.com/63967786/203847930-18460281-6681-40df-9dc4-a95cd1ed951d.png)

That's the Mods folder

**Comment by MegAmi24** [comment]
Is there a mod.ini file in the GLShaders folder? If there is, can you show it?

**Comment by h57758** [comment]
> Is there a mod.ini file in the GLShaders folder? If there is, can you show it?

![Screenshot_2022-11-24_19-41-46](https://user-images.githubusercontent.com/63967786/203849356-a3c67dde-2d86-486c-986d-5135752e251a.png)
Yup

**Comment by Mefiresu** [comment]
Rename your "Mods" folder to "mods" (lowercase).

**Comment by h57758** [comment]
Thanks, it worked!
