### ISSUE TITLE
[All Revisions, Windows] DX11 invokes a crash and/or graphical corruption when there is no DX11 shaders found.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#139]
So, to give this a description: There's a bug with the DX11 renderer where if there's no shaders for DX11 detected by v5 or v5u, the fallback shaders that it tries to load cause the engine to crash. But, depending on one's setup, it can have one of few effects. I know of only two, but they are:

1. If using an AMD setup (for GPU), the engine will cause a massive graphical corruption, and eventually crash. this was reported by RestGhost and MainMemory in the Retro Engine discord, both of which have AMD GPU's.

2. If using an Nvidia setup (like me, who's running a GTX 1060), the engine will just display a black screen and eventually close without *any* graphical corruption.

I'm not sure what the real cause is, but it fixes completely when you copy over the shaders folder from the repository into a data folder for the games you play, or have the shaders as a mod and have them enabled on startup.

i believe this is related to #133 as well.

**Comment by MainMemory** [comment]
My CPU is `AMD Ryzen 9` and my GPU is `AMD Radeon RX 5700 XT`, if it helps.

**Comment by stxticOVFL** [comment]
Merging into #133.
