### ISSUE TITLE
No rule to make target after linking RSDK

### ISSUE THREAD

**Issue by remivamp** [Rubberduckycooly/RSDKv5-Decompilation#14]
System: Archlinux
Error: Build

done dependencies/all/miniz/miniz.c
linking RSDK...
: bin/Linux/GL3/RSDKv5
done linking RSDK
make: *** No rule to make target 'bin/obj/Linux/Game/Game/Game.o', needed by 'bin/Linux/GL3/Game.so'.  Stop.

The compiling of other stuff like 3DScene and what not was omitted since that all worked without errors

Also the pre-compiled version is looking for libglew.so.2.1 which it can't find

**Comment by tedmakestuff** [comment]
I have the same issue as well, I'm compiling on a Raspberry Pi 400, hoping to run Sonic Mania natively without the use of Wine, I own the game and it's DLC legally on Steam and Nintendo Switch.

**Comment by MGRich** [comment]
If you just want to compile RSDKv5, pass `RSDK_ONLY=1` to the make command.
Else, create a symbolic link using `ln -s` to the `SonicMania` folder of the Mania repository named `Game`. (ex: `ln -s path/to/mania Game`)
