### ISSUE TITLE
Tails assist is broken and unusable

### ISSUE THREAD

**Issue by ToeGit** [Rubberduckycooly/RSDKv5-Decompilation#140]
When trying to use Tails to fly to some area of any level, you will just fall almost instantly

**Comment by LittlePlanetCD** [comment]
this is not an RSDKv5 bug, this is a Sonic Mania issue.

This was fixed a while ago, you are on an outdated build

**Comment by ToeGit** [comment]
But wasn't the latest version for RSDKv5 released on August 15th?

**Comment by LittlePlanetCD** [comment]
the bug comes from the Sonic Mania code, not RSDKv5.

if you want to fix it, you need to build the latest commits for the platform you're playing on.

What platform are you playing Sonic Mania on right now?

**Comment by ToeGit** [comment]
Android. AND BEFORE YOU SAY ANYTHING: I do not own a PC.

**Comment by LittlePlanetCD** [comment]
You'll have to wait for a new release, then.

There was a test release posted in the Retro Engine discord if you want to try it. You can find a server invite in the repository's readme.

**Comment by stxticOVFL** [comment]
Was one of the first bugs fixed as Cosmic said.
