### ISSUE TITLE
I'm not sure if I'd call this an issue, but it's an annoyance.

### ISSUE THREAD

**Issue by godreborn** [Rubberduckycooly/RSDKv5-Decompilation#141]
I compiled the android version yesterday.  everything works.  however, it asks which folder I want to run the game from every time I open the game.  then, it asks if I'd like to start the game.  is there any way to save these answers for next boot, so we don't have to do this every time I boot up sonic mania?  thanks.

**Comment by MegAmi24** [comment]
If the devs could implement this they would, but Android's limitations simply don't allow for that.

**Comment by godreborn** [comment]
alright, thanks for answering.  does the fact that it asks where you'd like to boot the game mean it can now be booted from anywhere on the sd card instead of RSDK/v5 on root?

**Comment by MegAmi24** [comment]
Yes, that's why it asks.
