### ISSUE TITLE
[Android, v5] [Sonic Mania Plus] Black Screen, different GPU

### ISSUE THREAD

**Issue by Caco-o-sapo** [Rubberduckycooly/RSDKv5-Decompilation#143]
I tried to install on my Android device, and some versions work and some don't idk why. In the versions that doesn't work the screen is black and I can't see nothing. But in a older version (of the Data.rsdk) is works fine. I saw that some GPUs doesn't work but mine is PowerVR and idk.

**Comment by stxticOVFL** [comment]
Probably user error considering a specific Data.rsdk works.
