### ISSUE TITLE
[V5U] game.xml mods override entirely the gameconfig

### ISSUE THREAD

**Issue by Leonx254** [Rubberduckycooly/RSDKv5-Decompilation#144]
As seen in below, the moment i loaded a mod containing a game.xml file, I lost complete access to s2's gameconfig, making it impossible to play anything other than the already loaded level or the one stage this game.xml contains

![RSDKv5U-sdl2_ltrDMc5Gbx](https://user-images.githubusercontent.com/59059689/205169964-d538ae54-332f-440b-b06c-d220052c95d3.gif)

**Comment by stxticOVFL** [comment]
Fixed as of the recent commits.
