### ISSUE TITLE
[v5U] F5 hot-reloading doesn't reload assets or scripts in legacy modes

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#147]
Pressing F5 to hot-reload the scene in the legacy v3 or v4 modes doesn't actually reload any sprites, sfx, scripts, etc., all it does is restart the current scene. It does reload assets in the separate v3/v4 decomps, just not here.

**Comment by stxticOVFL** [comment]
(enhancement tag because I think there needs to be reworks done to include this)

**Comment by stxticOVFL** [comment]
Think this was discussed in Discord already
