### ISSUE TITLE
[v5U Legacy Mode] Hitting a checkpoint and loading a new level puts Sonic in that checkpoint's coordinates but in the new level

### ISSUE THREAD

**Issue by MarioMastr** [Rubberduckycooly/RSDKv5-Decompilation#148]
e.g. Entering EHZ1 and hitting the checkpoint in the middle of the stage and then loading Act 2 puts you in between an item box and a spring, and it makes a lovely sound. This happens with both the decompiled scripts and with bytecode. 

https://user-images.githubusercontent.com/84964352/209083786-e27ad777-baf8-4f7d-bb6a-9779bf2815d1.mp4

**Comment by LittlePlanetCD** [comment]
This is intended behavior of v5u, as it happens in both the decompilation and in Sonic Origins itself.
