### ISSUE TITLE
game dont work

### ISSUE THREAD

**Issue by horay133** [Rubberduckycooly/RSDKv5-Decompilation#149]
steam ver of data.rsdk gives me a white screen and crash after 10 sec i think

**Comment by LittlePlanetCD** [comment]
Did you forget to include a Game.dll with the RSDKv5 executable?

**Comment by horay133** [comment]
what is this

**Comment by horay133** [comment]
i dont see a file named game.dll

**Comment by horay133** [comment]
im on win 10

**Comment by LittlePlanetCD** [comment]
You're supposed to build RSDKv5 and the Sonic Mania Decompilation, the latter providing a Game.dll for you to use.

**Comment by LittlePlanetCD** [comment]
You can find the Mania Decompilation here: https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation

**Comment by horay133** [comment]
but how do i get the plus Stuff

**Comment by MarioMastr** [comment]
To get plus you have to build the app yourself since distributing plus enabled apps aren’t allowed

**Comment by horay133** [comment]
how do i do that
