### ISSUE TITLE
Controller support improvements for DX9/DX11 builds of RSDKv5 and RSDKv5u

### ISSUE THREAD

**Issue by TTTTTsd** [Rubberduckycooly/RSDKv5-Decompilation#15]
Currently, the EXE crashes upon detecting specific types of controllers, notably DualShock 4 and certain Bluetooth controllers through Steam's built-in controller support (Nintendo Switch Pro Controller)

While it is likely a byproduct of Sonic Mania's controller handling, if it could at all be fixed to improve controller compatibility across all versions, it would be much appreciated! Controllers work better across the board on the GL and SDL builds currently, and DX builds are a little left behind in this regard.

Thanks!

**Comment by Rubberduckycooly** [comment]
I've looked into it a bit, and it seems to crash GetCursorPos when a DS4 controller is plugged in for whatever reason. Since GL & SDL builds work I'm going to put this one on my backlog for a while until I fix more prominent bugs since I'm stumped as to what's wrong.

**Comment by Benji7010** [comment]
> I've looked into it a bit, and it seems to crash GetCursorPos when a DS4 controller is plugged in for whatever reason. Since GL & SDL builds work I'm going to put this one on my backlog for a while until I fix more prominent bugs since I'm stumped as to what's wrong.

I know this ain't constructive, but I think it's funny that this problem is now labeled urgent after supposedly being put on the backlog.
