### ISSUE TITLE
[Android] LoadingIcon.java index out of bounds crash

### ISSUE THREAD

**Issue by TraceEntertains** [Rubberduckycooly/RSDKv5-Decompilation#152]
With a default Data.rsdk file and apk based off of latest commits of `Sonic-Mania-Decompilation`, `RSDKv5-Decompilation`, `UltrawideMania`, and `ManiaTouchControls` (at this time atleast), the game immediately crashes after the loading screen.
A stack trace for the error is attached (although the rest of the log isn't as I did not copy that).

If further logs are needed please contact me on Discord: `TraceEntertains#5092`

[partialstacktrace.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/10326793/partialstacktrace.txt)

**Comment by LittlePlanetCD** [comment]
I've built all the current commits and i have not been able to reproduce this.

Could you elaborate on what device you're running from?

**Comment by TraceEntertains** [comment]
A Samsung S21 Ultra (512GB/16GB) US Model

**Comment by TraceEntertains** [comment]
Ah, it was due to a lack of shaders.
