### ISSUE TITLE
Error LNK2001 when trying to compile OGL statically on Windows with VS2022

### ISSUE THREAD

**Issue by YesterPlay80** [Rubberduckycooly/RSDKv5-Decompilation#155]
Trying to compile RSDKv5Us OpenGL build for Windows x64 with Visual Studio I'm getting this error:

`Error - LNK2001 - unresolved external symbol "__imp_strspn". - RSDKv5U-ogl - C:\RSDKv5-Decompilation\RSDKv5U\glfw3_x64.lib(input.obj) - 1`

Compiling a dynamic build with DLLs (/MD) works, it's just the static one (/MT) resulting in this error.  

When trying to compile a x86 build (just to see if that'd work) I even get one more error: 

`Error - LNK2001 - unresolved external symbol "__except_handler4_common". - RSDKv5U-ogl - C:\RSDKv5-Decompilation\RSDKv5U\MSVCRT.lib(chandler4gs.obj) - 1`

DX9 and DX11 (after applying PR#153) compile just fine statically. 
Am I doing something wrong or is there something missing from the source files? Or should we stick to only DX9/11 and/or SDL2 for Windows entirely?

**Comment by stxticOVFL** [comment]
Static builds with GL are really weird; I don't think I got it working on my end either. Considering this isn't _required_ because dynamic building works just fine, I'm gonna close it. It would be really nice to look into at some point, though.
