### ISSUE TITLE
Game Small Screen In SnapDragon 400 or 410

### ISSUE THREAD

**Issue by yehyasabry** [Rubberduckycooly/RSDKv5-Decompilation#158]
I have this problem in my phone when i open sonic mania the screen always small 

How to fix this problem 
Thanks For reading

**Comment by yehyasabry** [comment]
Any one can help me please

**Comment by LittlePlanetCD** [comment]
where did you get your apk from

**Comment by yehyasabry** [comment]
From Github

**Comment by yehyasabry** [comment]
Any one know thing to help

**Comment by LittlePlanetCD** [comment]
this bug was fixed a while ago as far as i know.

if you want to fix this yourself, you'd have to build the APK yourself with the latest commits.

**Comment by yehyasabry** [comment]
How to bulid it

**Comment by yehyasabry** [comment]
I think with android studio is that true

**Comment by yehyasabry** [comment]
But im not have pc any one can help

**Comment by LittlePlanetCD** [comment]
You'd need a windows PC to build it, there's really no other way afaik.

**Comment by yehyasabry** [comment]
Ok

**Comment by Luccas7383** [comment]
Does anyone have the apk in the latest version that I already tried to compile but it wouldn't

**Comment by stxticOVFL** [comment]
Plus-enabled APK distribution is not allowed. Try the preview build in REMS.
