### ISSUE TITLE
Cannot Compile from Git on OpenSUSE Tumbleweed 20230119

### ISSUE THREAD

**Issue by SolarNyan** [Rubberduckycooly/RSDKv5-Decompilation#159]
When attempting to compile a native Linux decomp on OpenSUSE Tumbleweed, I get this error back in terminal:

```
***************:~/Sonic-Mania-Decompilation/dependencies/RSDKv5> make RSDK_REVISION=2
linking RSDK...
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: cannot find -lasound: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:241: bin/Linux/GL3/RSDKv5] Error 1
```

I'm assuming this is a lack of a dependency, but there is no documentation I can find anywhere for someone compiling this on OpenSUSE, and they use their own package manager (zypper) rather than the main popular ones like apt, dnf, or pacman, so the info in the readme.md unfortunately did not help. Any suggestions as for what I should do, or maybe someone knows which dependency I'm lacking?

**Comment by Mefiresu** [comment]
The `asound` lib is from ALSA. You need the ALSA development libraries:
```sh
sudo zypper install alsa-devel
```

**Comment by SolarNyan** [comment]
> The `asound` lib is from ALSA. You need the ALSA development libraries:
> 
> ```shell
> sudo zypper install alsa-devel
> ```

Thank you!!! This got it working, and I was able to compile both the regular RSDKv5 and Extra-Slot Amy with zero issues so far. :D

AFAIK that's the only dependency that isn't mentioned in some form on the readme, so it might help other OpenSUSE users if it's added onto there, especially since some of the dependencies for OpenSUSE are named differently.

**Comment by Mefiresu** [comment]
It's not mentioned in the documentation because it wasn't needed for other distros.
Maybe the development package on OpenSUSE is missing a dependency on `asound`? In that case it might be good to contact the OpenSUSE package maintainers in order to fix it upstream.
