### ISSUE TITLE
[DX11] Slow Videos

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/RSDKv5-Decompilation#16]
When compiling the engine with DX11, videos for Sonic Mania play _way slower than they should_. DirectX 9, OpenGL 3, and SDL2 _**do not have this issue**_.

Tested on most recent commit at the time of this issue being edited ("fix some stragglers" by Rubberduckycooly), with v5U.

Footage:
https://user-images.githubusercontent.com/79285355/185004992-c2ba7883-29ab-41d6-820b-27fb02d226c7.mp4

**Comment by MGRich** [comment]
Do you mean the DirectX 11 backend? Does still happen in the most recent commits?

**Comment by RetroForever** [comment]
Edited the issue to clarify further, and yes, this does still happen on the most recent commits

**Comment by RetroForever** [comment]
With the help of REMS, it seems this is simply an issue with my build. Happens on Steam too
