### ISSUE TITLE
Reconfirm path of the game

### ISSUE THREAD

**Issue by Gamma102** [Rubberduckycooly/RSDKv5-Decompilation#162]
Path confirmation appears every time on startup
RSDKv5_ManiaDecomp_70c113c

**Comment by LittlePlanetCD** [comment]
This is how the android app is programmed.

Main reason why is it get around Android's storage permissions being a bit of a pain to work with as of recent.

It's weird but it gets the job done.

~~I personally blame Google for this~~

**Comment by Gamma102** [comment]
> This is how the android app is programmed.
> 
> Main reason why is it get around Android's storage permissions being a bit of a pain to work with as of recent.
> 
> It's weird but it gets the job done.
> 
> ~I personally blame Google for this~

It's still easier than inserting a cartridge into console =)
But in the previous version it wasn't - RSDKv5_ManiaDecomp_6f23fd8

**Comment by LittlePlanetCD** [comment]
> > This is how the android app is programmed.
> > Main reason why is it get around Android's storage permissions being a bit of a pain to work with as of recent.
> > It's weird but it gets the job done.
> > ~I personally blame Google for this~
> 
> It's still easier than inserting a cartridge into console =) But in the previous version it wasn't - RSDKv5_ManiaDecomp_6f23fd8
> 6f23fd8.mp4

previous versions also couldn't use the RSDK/v5 folder normally on up-to-date phones.

there was a lot of reports of the app not loading at all until paths were done like how they are now.

~~google sucks~~

**Comment by stxticOVFL** [comment]
Not a bug: required for Android 11+ to actually work properly.
