### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by godreborn** [Rubberduckycooly/RSDKv5-Decompilation#163]
I figured out what the problem was originally (was using an old version of RSDKv5), when it comes to the black screen problem for others.  however, now, it either works perfectly like for me or one of my friends, or it has constant crashes like with my mom's phone or another friend's.  I don't understand what the problem is.  I thought I did something wrong somehow, but I even used a bat file to do everything at the very end, and still same problem.  could it have to do with putting a GameAPI symlink in the jni folder?  is that even necessary?

**Comment by LittlePlanetCD** [comment]
these crashes seem to be phone-dependent.

the user who worked on the android port has done what they can to fix it to work on a lot more devices. if it doesn't work on some phones, it cant really be troubleshooted unless we have device info, such as:

-the phone model
-the cpu and gpu of the phone.

you can get these from an app called CPU-Z iirc

**Comment by stxticOVFL** [comment]
GameAPI symlink isn't necessary, no. Much more info is needed as Cosmic said. Closing until then.
