### ISSUE TITLE
Issue May Be Back (Black Screen)

### ISSUE THREAD

**Issue by godreborn** [Rubberduckycooly/RSDKv5-Decompilation#165]
the previous update didn't have the black screen problem for me or any of my friends.  however, I compiled a new build, with the latest changes, and it seems to be hit or miss.  it works fine for me, but two of my friends are getting black screens w/ sound working.  not sure what the problem is.

**Comment by stxticOVFL** [comment]
Probably some sort of user error? I've seen no one else talk about it.

**Comment by godreborn** [comment]
> Probably some sort of user error? I've seen no one else talk about it.

actually, I was using RSDKv5 recursively when doing git clone from the Sonic Mania repo.  it was using an older build of the repo, so I git cloned the RSDKv5 repo directly.  no more black screen on anyone's phone.  though, what's odd is that it always worked on my phone regardless. 

I'll try to get the information about my mom's phone for the crashing issue this weekend.  this is a known issue?  my mom's semi-works.  sometimes it works fine; other times it crashes at boot.  it seems to work fine if it boots.  the previous build works fine for seemingly everyone, so I thought I might've forgotten to do something here, but it's always worked fine on my phone.
