### ISSUE TITLE
[Request] Lower the OpenGL version requeriments to reach more hardware?

### ISSUE THREAD

**Issue by vanfanel** [Rubberduckycooly/RSDKv5-Decompilation#166]
Hi there,

The SonicMania decomp built for the GLFW subsystem requires OpenGL 3.3 (as specified in 
https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/4a458a043dfd6122d11782ad190aac45867e1245/RSDKv5/RSDK/Graphics/GLFW/GLFWRenderDevice.cpp#L53)

However, it can be run in GNU/Linux systems like the Raspberry Pi 4 where the max OpenGL version is 2.1, with:
`MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 ./RSDKv5`

Everything works good that way: There are no features that are missing with OpenGL 2.1, and I believe the OpenGL 3.3 decision was a bit too much, even for the basic CRT-like shaders that the engine supports.

So, would it be possible to have the OpenGL version lowered to 2.1 instead of 3.x? Devices supporting OpenGL 2.1 are much more numerous, and in fact the original game executable runs in them.

NOTE that lowering the GLSL version would also be necessary.

**Comment by stxticOVFL** [comment]
GL version can now be controlled using `_GLVERSION=33` (or whatever you want it set to.)
