### ISSUE TITLE
[GL3] Window doesn't properly refresh

### ISSUE THREAD

**Issue by RetroForever** [Rubberduckycooly/RSDKv5-Decompilation#17]
In OpenGL 3 compiles of the engine, the video options of Window Size and Full Screen both function incorrectly. Once the setting takes effect, they go into a completely black screen, however, it is only visual as the game itself still receives inputs and plays audio fine.

Tested on most recent commit at the time of this issue being submitted (:sob: by Chuli), with v5U.

~~also this is completely unrelated but the icon doesn't show up in the taskbar specifically for GL3 and that makes me irrationally angry~~

**Comment by MGRich** [comment]
Something is wrong with `RefreshWindow` that breaks stuff like full-screening and changing the window size: I'll look into it later.

**Comment by RetroForever** [comment]
Much appreciated!

**Comment by MGRich** [comment]
wrong issue oops
