### ISSUE TITLE
Sony DualSense crash

### ISSUE THREAD

**Issue by Hereward-GH** [Rubberduckycooly/RSDKv5-Decompilation#180]
Everytime I connect my DualSense on pc, RSDKv5 crash.
I don't know why this happens.

**Comment by Hereward-GH** [comment]
I've tried with Steam opened and closed... nothing.

**Comment by LittlePlanetCD** [comment]
you need to use a renderer other than DX9 or DX11 that can support Playstation controllers.

that, or you use Steam Input with RSDKv5 in your library to make the game work.

**Comment by stxticOVFL** [comment]
Duplicate of #15.
