### ISSUE TITLE
[Linux] [SDL2] Gamepad functionality broke in a recent commit

### ISSUE THREAD

**Issue by awe444** [Rubberduckycooly/RSDKv5-Decompilation#184]
Hi, I'm building RSDKv5U on Linux with Plus DLC using `-DRSDK_USE_SDL2=1` flag and `make SUBSYSTEM=SDL2`. 

For commits up to and including https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/7718f7c6864ce19b73937d7aced6a4be76f344a1 the resulting binary plays flawlessly. My XBox controller works everywhere in the game, and XBox button icons appear.

Starting with https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/481464a1d3c479cec159f422e1def4bc04dae373 from 2 weeks ago: the resulting build has crippled/broken gamepad support. It still recognizes gamepad input in menus (start/confirm/back), but I see keyboard button icons instead of the expected Xbox button icons. Once I get in-game, I can't move the character at all or open the menu with the gamepad.

**Comment by niuus** [comment]
> Hi, I'm building RSDKv5U on Linux with Plus DLC using `-DRSDK_USE_SDL2=1` flag and `make SUBSYSTEM=SDL2`.
> 
> For commits up to and including [7718f7c](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/7718f7c6864ce19b73937d7aced6a4be76f344a1) the resulting binary plays flawlessly. My XBox controller works everywhere in the game, and XBox button icons appear.
> 
> Starting with [481464a](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/481464a1d3c479cec159f422e1def4bc04dae373) from 2 weeks ago: the resulting build has crippled/broken gamepad support. It still recognizes gamepad input in menus (start/confirm/back), but I see keyboard button icons instead of the expected Xbox button icons. Once I get in-game, I can't move the character at all or open the menu with the gamepad.

I can confirm this. I'm using a build from 2023-03, it used to work with the USB controller (through X360CE) as Player 1, but now only the keyboard is being recognized. I noticed this first as mods that affect the HUD like PS4 / PS5 buttons don't do anything now. The difference here being that I can move the player and menus with the USB controller, but it is only recognized as Player 2 (Tails) on a Sonic+Tails game, with the keyboard controlling Player 1 (Sonic).

**Comment by stxticOVFL** [comment]
Let me know if this didn't actually fix it; there could be another part to it that I couldn't do right away because I need to verify.

**Comment by awe444** [comment]
Thanks for working on this issue. I just did a build but unfortunately the issue is still there. It continues to show keyboard button icons in menus, and can't control the player in game.

**Comment by awe444** [comment]
@niuus are you also still observing this issue with latest commits?

**Comment by ZeptoBST** [comment]
Appears to still be a problem a year later.
