### ISSUE TITLE
Mac Won't Build

### ISSUE THREAD

**Issue by AwayCoast23465** [Rubberduckycooly/RSDKv5-Decompilation#186]
The mac comes up with this error: 

Build input file cannot be found: '/Users/rileydukes/RSDKv5-Decompilation/dependencies/mac/RSDKv5.entitlements'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

**Comment by MarioMastr** [comment]
Yeah that's simply because there isn't regularly a RSDKv5.entitlements file. You can grab the file (and dependencies for that matter) from here: https://github.com/Sappharad/RSDKv5-Decompilation

**Comment by AwayCoast23465** [comment]
now i get this:
 /Users/rileydukes/RSDKv5-Decompilation/dependencies/mac/Game.dylib /Users/rileydukes/RSDKv5-Decompilation/dependencies/mac/Game.dylib: No such file or directory
