### ISSUE TITLE
[v5U] Mod assets are always reloaded every time a scene loads in legacy modes

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#189]
In the v3 and v4 legacy modes. every time a scene loads, no matter if it's from the Dev Menu, restarting the currently loaded scene, loading a new scene, or F5 hot-reloading, the engine will always reload every mod asset. The standalone v3/v4 decomps do this too, but here it gets annoying fast since you have to sit through a loading bar every time. [Potential reworking was mentioned in #147](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/issues/147#issuecomment-1421313284), maybe this could be addressed in it somehow?

**Comment by stxticOVFL** [comment]
Going to presume this isn't an issue anymore due to the referenced commit. Feel free to reopen if it's still not satisfactory.
