### ISSUE TITLE
Mod "ONGAMESTARTUP" callbacks aren't called when reloading the engine after changing mods

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#192]
It seems mods that have callbacks that get called on game startup don't get said callbacks called when reloading the engine after changing mods.
MegAmisDevTools has a game startup callback, used for setting the default characters. In this video, I use it to set them to Knuckles & Sonic. Note how after reloading the engine, it becomes the default Sonic & Tails.

https://user-images.githubusercontent.com/7158344/232260668-93df2037-156b-450f-a527-616e01213978.mp4

**Comment by stxticOVFL** [comment]
This fix slightly changes the position of the callback; please let me know if this causes any issues.

**Comment by MegAmi24** [comment]
The fix mostly works, but it's causing mods such as MegAmisDevTools to have a seemingly random crash of crashing when the callback is called:
![image](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/7158344/3960050e-c5f6-44d4-a33c-72aa5bac3f53)

In addition, there's also a chance it crashes on startup with this error (this is unrelated to #205):
![image](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/7158344/dc472b4b-8f3f-4d3e-83b1-30b47f32e0db)
)
