### ISSUE TITLE
[v5U] Videos don't play properly in Legacy v3 Mode

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#194]
Videos don't seem to play in Legacy v3 Mode at all. I checked the code and stuff for it is there, so it is intended to work, yet it doesn't. I'm running in Data Folder Mode with the Videos folder in the Data folder, as v5U expects.
Not sure if this is something related to the OGV files themselves or not (I'm using different files compared to the original Steam videos), but it could be likely. Videos work as intended in v5 Mode.
![image](https://user-images.githubusercontent.com/7158344/235174589-337305b6-f512-4d25-8352-5097cb124812.png)

**Comment by sonicdemo** [comment]
The folder needs to be named "Video". If it doesn't work, i'm sorry.

**Comment by MegAmi24** [comment]
Ok so turns out I had my folder named wrong the whole time, oops.

The videos do look like this ingame and don't play audio, though I assume this isn't exactly a priority to fix.
![image](https://user-images.githubusercontent.com/7158344/235177737-a9d3fd60-c25d-40dc-a485-c75e6212c676.png)
