### ISSUE TITLE
it's not entirely clear how to enable dlc plus :\

### ISSUE THREAD

**Issue by texi7** [Rubberduckycooly/RSDKv5-Decompilation#199]
"Plus DLC is available as a toggle in the system Settings app under "RSDKv5" (at the bottom)"

In which settings exactly? iPhone settings? in the files? I seriously don't understand how to enable dlc :(
You can play paintball through Devmode, but encore doesn't work(

**Comment by MegAmi24** [comment]
This repo doesn't maintain the iOS port, do not ask questions related to it here.
To answer your question though, yes, you go in the iPhone settings, that's what "the system Settings app" means.

**Comment by AnthraxBass** [comment]
I've got the same question regarding Windows version

**Comment by MegAmi24** [comment]
> I've got the same question regarding Windows version

You need to build the decomp manually.

**Comment by AnthraxBass** [comment]
> > I've got the same question regarding Windows version
> 
> You need to build the decomp manually.

Is it possible to build with something other than Visual Studio ? I hate it, bc it's very hard to remove later, it takes alot of space, and it's too heavy on my system.

**Comment by MegAmi24** [comment]
> Is it possible to build with something other than Visual Studio ? I hate it, bc it's very hard to remove later, it takes alot of space, and it's too heavy on my system.

You can build it using CMake.
