### ISSUE TITLE
RSDKv5 vs v5U? (in the terms of Sonic Mania)

### ISSUE THREAD

**Issue by SirGamers** [Rubberduckycooly/RSDKv5-Decompilation#200]
yea whats the difference between them

**Comment by Sonic-Geared** [comment]
basically, v5 is the normal v5 that Mania runs on, but v5U has retrocompatibility with v4 & v3, but in terms of Mania, i can't really tell the difference, there might be some different stuff in there, maybe new stuff or even fixes with the engine itself that normal v5 had, but i recommend waiting to a answer from someone that has actual knowledge about the differences.

**Comment by Sonic-Geared** [comment]
basically, v5 is the normal v5 that Mania runs on, but v5U has retrocompatibility with v4 & v3, but in terms of Mania, i can't really tell the difference, there might be some different stuff in there, maybe new stuff or even bug fixes with the engine itself that normal v5 had problems with, but i recommend waiting to a answer from someone that has actual knowledge about the differences.

**Comment by SCOTT0852** [comment]
V5U is the version of V5 used in Sonic Origins that is compatible with V3 (CD), V4 (1/2), and V5 (3) data. Standard V5 is only capable of loading V5 data. For the purposes of loading a normal Mania data file, it should make no difference.

This is not an issue with the decomp, so you shouldn't have opened an issue for this.
