### ISSUE TITLE
(Nintendo Switch) fatal error: dyn.h: No such file or directory

### ISSUE THREAD

**Issue by sonicdemo** [Rubberduckycooly/RSDKv5-Decompilation#203]
Tried building RSDKv5 for the Switch and i failed with this error:
```
make PLATFORM=Switch
creating NACP...
compiling RSDKv5/main.cpp...
In file included from RSDKv5/main.cpp:1:
RSDKv5/RSDK/Core/RetroEngine.hpp:493:10: fatal error: dyn.h: No such file or directory
  493 | #include <dyn.h>
         |                ^~~~~~~
compilation terminated.
make: *** [bin/obj/Switch/OGL/RSDKv5/RSDKv5/main.o] Error 1
```
Have no idea if this is an issue on my side or it's an regular decomp bug, help needed

**Comment by sonicdemo** [comment]
Ok, so i put this file and others from the libnx-dyn directory to the devkitpro folder, and now it seems like i got a different error now. ```
make PLATFORM=Switch
creating NACP...
compiling RSDKv5/main.cpp...
RSDKv5/main.cpp:8:10: fatal error: GameMain.h: No such file or directory
    8 | #include <GameMain.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:229: bin/obj/Switch/OGL/RSDKv5/RSDKv5/main.o] Error 1
```

**Comment by stxticOVFL** [comment]
Use the CMake, not the makefile. Look in the cmake-docs branch for more info.
