### ISSUE TITLE
Solved, but can't use mods.

### ISSUE THREAD

**Issue by usaginoshoujo** [Rubberduckycooly/RSDKv5-Decompilation#209]
I've been at this for days and only found out that it wasn't compiling because nobody's bothered to update the readme. #178 
Now it just refuses to run.

> (deck@steamdeck Sonic Mania Decomp)$ ./RSDKv5U 
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
Segmentation fault (core dumped)
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/12047728/log.txt)

**Comment by stxticOVFL** [comment]
The new Readme is work in progress (see #204), though this looks to be PortAudio being incompatible with the Steam Deck somehow. I'd try building with `USE_SDL_AUDIO` enabled (requiring SDL2) and see if that helps?

**Comment by usaginoshoujo** [comment]
Still crashes, log file's basically the same.

**Comment by usaginoshoujo** [comment]
Fixed by #206, but is there any sort of integrated mod menu? If not, are there plans to make one? There seems to be no way to manage mods.

**Comment by MegAmi24** [comment]
There's a mod menu in the Dev Menu.

**Comment by usaginoshoujo** [comment]
> There's a mod menu in the Dev Menu.

It just says "Mod loading done!" and goes back to the dev menu.

**Comment by usaginoshoujo** [comment]
It's case sensitive. The folder needs to be all lowercase.
