### ISSUE TITLE
Sonic CD (Origins) has a lot of strange behavior

### ISSUE THREAD

**Issue by usaginoshoujo** [Rubberduckycooly/RSDKv5-Decompilation#216]
Not really sure what to call it, just watch the attached video.
The assets are from Origins (Switch), but the audio files I pulled from the Android version (aside from the Amy and Knuckles sfx).

https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/134822401/791d4b2e-a8ec-4604-b7c3-421f59724dff

[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/12179480/log.txt)

**Comment by LittlePlanetCD** [comment]
This is already known and will be fixed later; Sonic Origins Plus added a new PlayerObjectInteraction called "C_ENEMY" that's currently not implemented in the RSDKv5u Decompilation (and only partly implemented in the RSDKv3 standalone decompilation).

**Comment by LittlePlanetCD** [comment]
Also, I can tell you're running on a *very old* version of the RSDKv5u decompilation. Your clouds are not moving.

**Comment by usaginoshoujo** [comment]
> Also, I can tell you're running on a _very old_ version of the RSDKv5u decompilation. Your clouds are not moving.

I downloaded the current Windows release due to #214. As there is no guide for cross-compiling the Windows build, this is the only option. I initially was going to re-pack the audio files into the Data.rsdk, but RSDKv5Pack (unsurprisingly really) packs it as RSDKv5, and that causes the Decomp to fail loading the game because it can't find Game.so.

**Comment by LittlePlanetCD** [comment]
Cross-compiling the windows build...?
What platform are you on? Windows or Linux?

**Comment by usaginoshoujo** [comment]
> Cross-compiling the windows build...?
> 
> the only real way to build the windows version on linux is like... through a VM with a Windows operating system, i think?
> 
> otherwise to fix #214 temporarily for the linux version, just rename the .ani file extensions in Data/Animations to .Ani.

I'm running the Windows build on Linux because of the case sensitivity issues with the engine. The calls are made for multiple variations of file/folder names (ByteCode, Bytecode, Sonic.ani, Sonic.Ani), so I would have to either duplicate or symlink every file as the error comes up. The much simpler solution is to just run the Windows build, since Wine resolves this automatically.
