### ISSUE TITLE
(RSDKv5u) CD Missing Parallax (???)

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#22]
Sonic CD seems to be missing parallax in stages, most notably in Palmtree Panic 1, where the clouds in the sky just don't move, when in the mobile port (and in Origins too) the clouds move.

![image](https://user-images.githubusercontent.com/24783625/185353753-bc05705e-4115-4361-9716-b7ffc4e20af6.png)

**Comment by Rubberduckycooly** [comment]
fixed in 360a4bab238f6bc47b82d9103712f3c037d2a63d
