### ISSUE TITLE
GitHub release archive does not include submodules

### ISSUE THREAD

**Issue by ADKaster** [Rubberduckycooly/RSDKv5-Decompilation#222]
When downloading https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/archive/refs/tags/v1.0.0-win.tar.gz , the dependencies folder is empty. Unless I'm mistaken, this means that the source release tarball can't be used to compile the project.

**Comment by MegAmi24** [comment]
Release source code archives are automatically generated by GitHub, so there's nothing that can be done about this unfortunately.
