### ISSUE TITLE
RSDKv5 asking for portaudio.pc but I have portaudio-2.0.pc

### ISSUE THREAD

**Issue by Kelvfimer** [Rubberduckycooly/RSDKv5-Decompilation#234]
Hello 

When compiling on linux latest sonicmania commit I have a warning messages stating

Package portaudio was not found in the pkg-config search path.
Perhaps you should add the directory containing `portaudio.pc'
to the PKG_CONFIG_PATH environment variable
No package 'portaudio' found

The thing is that my toolchain has portaudio file but it is portaudio-2.0.pc. If I rename poraudio-2.0.pc to portaudio.pc the issue disappears.

Pls can you help me to fix this issue?

thx

**Comment by Mefiresu** [comment]
Makefile has been deprecated in favor of CMake a while back and the build documentation is in the process of being rewritten.

Try following these instructions instead: https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/tree/cmake-docs#how-to-build

**Comment by MSHectorCM** [comment]
thx for the answer @Mefiresu . I didn't know :)

Now I see that it is needed glew and glfw3. Are they mandatory packages now? as I don't have them in Emuelec and as far as I know the developer is not adding them to EMUELEC.

So the question is, is it possible to avoid glew and glfw3 in Linux?

-- Checking for module 'glfw3'
--   No package 'glfw3' found
could not find glfw, attempting to build from source
CMake Error at dependencies/RSDKv5/platforms/Linux.cmake:40 (add_subdirectory):
  add_subdirectory given source "dependencies/ogl/glfw" which is not an
  existing directory.
Call Stack (most recent call first):
  dependencies/RSDKv5/CMakeLists.txt:66 (include)


-- Checking for module 'glew'
--   No package 'glew' found
could not find glew, attempting to build from source
-- Configuring incomplete, errors occurred!

thx

**Comment by Mefiresu** [comment]
The only other backend for Linux is SDL2, which should be in EMUELEC:
```sh
cmake .. -DRETRO_SUBSYSTEM=SDL2
```

**Comment by MSHectorCM** [comment]
thx @Mefiresu 

I did cmake PLATFORM=Linux -DRETRO_SUBSYSTEM=SDL2 and it is still failing in the same way that makes no sense per the linux.cmake

is there something wrong?

thx

**Comment by MSHectorCM** [comment]
I had to added in a special way i doesn't work as cmake -DRETRO_SUBSYSTEM=SDL

thx for your help

KR

**Comment by Mefiresu** [comment]
Glad you figured it out!
