### ISSUE TITLE
Sonic origins rsdk

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [Rubberduckycooly/RSDKv5-Decompilation#241]
whenever I try to load in Sonic 3 and Knuckles from Sonic Origins, it opens the Sega logo with a black background and then stops from there, what do I do?

**Comment by MegAmi24** [comment]
There's no decompilation of the Origins version of S3&K, so the game won't work on the RSDKv5 decompilation.

**Comment by CHUCKECHEESETubeYT** [comment]
damnit! now what do i do!?

**Comment by MegAmi24** [comment]
Just play Origins if you want to play Origins S3&K.

**Comment by CHUCKECHEESETubeYT** [comment]
😒

**Comment by Sonic-Geared** [comment]
yeah, sorry buddy, but that's how it works like =/

**Comment by CHUCKECHEESETubeYT** [comment]
wouldn't be much easier for me to make a decompilation of S3&k for this version of the retro engine?

**Comment by Leonx254** [comment]
do it then, good luck.

**Comment by CHUCKECHEESETubeYT** [comment]
Fine! don't say i didn't warn you

**Comment by stxticOVFL** [comment]
👍
