### ISSUE TITLE
Selfbuilt APK crashes after selecting path

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [Rubberduckycooly/RSDKv5-Decompilation#246]
I built the APK myself, wanting to enjoy the DLC i bought on PC on my Android Tablet.

Upon launching it asks me to select a path (the same path i used with the binary from here and that worked) but it closes instantly right after.

Why does it refuse to work in my selfbuilt apk, but works in the one provided here?

**Comment by Mefiresu** [comment]
The Android currently has issues I've been trying to fix, try applying the changes in #245 to see if it works better for you.

**Comment by VorgonBattlecruiser** [comment]
> The Android currently has issues I've been trying to fix, try applying the changes in #245 to see if it works better for you.

i muddled my way through the build process, somehow, but without a detailed guide there isnt a chance in hell i could do any of what post #245 said.

Sorry, i guess im just gonna have to wait for your fix then!
