### ISSUE TITLE
Ghost Input with DualShock 4/DualSense on local builds

### ISSUE THREAD

**Issue by ActualMandM** [Rubberduckycooly/RSDKv5-Decompilation#25]
When building RSDKv5 locally, having a DualShock 4 or DualSense plugged in will cause constant ghost inputs to the game, only stopping when you unplug the controller. This does not happen with builds from GitHub Actions.

https://user-images.githubusercontent.com/15317421/185525817-222755c5-0c59-44f7-9acb-e010257337e1.mp4

**Comment by MGRich** [comment]
Duplicate of #15.
