### ISSUE TITLE
Why i get the small screen? 

### ISSUE THREAD

**Issue by akbar290420** [Rubberduckycooly/RSDKv5-Decompilation#256]
Why It's Like This? 
![Screenshot_20240226_210743](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/161325751/26b80f44-7c47-4f7d-bbd4-fd0538bf7217)
 

And My Log.txt 
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/14405015/log.txt)

And Can You Fixed My Log.txt? (if it's fix give me again)

**Comment by akbar290420** [comment]
Snapdragon 425?

**Comment by akbar290420** [comment]
Snapdragon 425

**Comment by egormese334** [comment]
Where did you got APK file?

**Comment by akbar290420** [comment]
From ThunderPlayz

**Comment by akbar290420** [comment]
But apk is same just the icon is it's not same

**Comment by MegAmi24** [comment]
We do not help people who pirated the game.

**Comment by akbar290420** [comment]
Ok

**Comment by akbar290420** [comment]
I'm sorry pirate you game

**Comment by akbar290420** [comment]
Actually it's not pirate it's RSDK v5 but with different icon and names
