### ISSUE TITLE
Smal screen

### ISSUE THREAD

**Issue by akbar290420** [Rubberduckycooly/RSDKv5-Decompilation#257]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/14414228/log.txt)

My Game Has The Smal Screen And You Know? My Snapdragon is 425

Is There Any Way To Fix My Log.txt? 

![Screenshot_20240227_121449](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/161325751/5093b833-f276-4365-a9b5-064a29b94f02)
There

**Comment by egormese334** [comment]
Where did you got APK?
