### ISSUE TITLE
Smal screen and please forgive me

### ISSUE THREAD

**Issue by akbar290420** [Rubberduckycooly/RSDKv5-Decompilation#259]
Hello again I'm actually not pirate the game but please forgive me

And Can you fix my log.txt? 
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/14419226/log.txt)

Screenshot
![Screenshot_20240227_121449](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/161325751/520ab120-7405-4f30-9480-7f009288d16b)

Snapdragon 425

**Comment by egormese334** [comment]
You need to build decomp manually on PC and not just download it from random source

**Comment by egormese334** [comment]
And please, don't open issues again because it was fixed ages ago and you're using really outdated build
