### ISSUE TITLE
The DLC

### ISSUE THREAD

**Issue by SparkingPlayer** [Rubberduckycooly/RSDKv5-Decompilation#26]
How to get the DLC ? Or i can't?

**Comment by tedmakestuff** [comment]
For Sonic Mania? I don't know how it works but I'm pretty sure if you have the DLC on Steam, when you install you get an updated RSDK, which gives the DLC, you gotta own it tho. I own Sonic Mania Plus both on Steam and Switch.

**Comment by breakthetargets** [comment]
Build the RSDKv5 decomp yourself.

**Comment by ViperAcidZX** [comment]
> For Sonic Mania? I don't know how it works but I'm pretty sure if you have the DLC on Steam, when you install you get an updated `Data.rsdk`, which gives the DLC, you gotta own it tho. I own Sonic Mania Plus both on Steam and Switch.

I tried that and even though I legally own Sonic Mania and the Plus DLC I can't get access to the the Plus content in the decomp. I tried re-installing the game and toggling Plus on and off in the DLC tab on the Steam client, it doesn't change the size of the `Data.rsdk` file for Sonic Mania.

**Comment by SparkingPlayer** [comment]
I think they said that soon we are going to have the android SM+ support though

**Comment by LittlePlanetCD** [comment]
> I think they said that soon we are going to have the android SM+ support though

android already supports Sonic Mania's Plus DLC.

You need to build the app yourself using Android Studio, or whatever works on the platforms you have available to you.

That is the only way you can access Plus.

**Comment by tedmakestuff** [comment]
> > For Sonic Mania? I don't know how it works but I'm pretty sure if you have the DLC on Steam, when you install you get an updated `Data.rsdk`, which gives the DLC, you gotta own it tho. I own Sonic Mania Plus both on Steam and Switch.
> 
> I tried that and even though I legally own Sonic Mania and the Plus DLC I can't get access to the the Plus content in the decomp. I tried re-installing the game and toggling Plus on and off in the DLC tab on the Steam client, it doesn't change the size of the `Data.rsdk` file for Sonic Mania.

Oh.. I just realised, it may actually be IN the `Data.rsdk`, just require some sort of argument/flag to enable the content, so that may need source modifications. Beyond that, I don't know anything.

**Comment by dremonq** [comment]
> > > For Sonic Mania? I don't know how it works but I'm pretty sure if you have the DLC on Steam, when you install you get an updated `Data.rsdk`, which gives the DLC, you gotta own it tho. I own Sonic Mania Plus both on Steam and Switch.
> > 
> > 
> > I tried that and even though I legally own Sonic Mania and the Plus DLC I can't get access to the the Plus content in the decomp. I tried re-installing the game and toggling Plus on and off in the DLC tab on the Steam client, it doesn't change the size of the `Data.rsdk` file for Sonic Mania.
> 
> Oh.. I just realised, it may actually be IN the `Data.rsdk`, just require some sort of argument/flag to enable the content, so that may need source modifications. Beyond that, I don't know anything.

build the app

**Comment by SparkingPlayer** [comment]
> > > > For Sonic Mania? I don't know how it works but I'm pretty sure if you have the DLC on Steam, when you install you get an updated `Data.rsdk`, which gives the DLC, you gotta own it tho. I own Sonic Mania Plus both on Steam and Switch.
> > > 
> > > 
> > > I tried that and even though I legally own Sonic Mania and the Plus DLC I can't get access to the the Plus content in the decomp. I tried re-installing the game and toggling Plus on and off in the DLC tab on the Steam client, it doesn't change the size of the `Data.rsdk` file for Sonic Mania.
> > 
> > 
> > Oh.. I just realised, it may actually be IN the `Data.rsdk`, just require some sort of argument/flag to enable the content, so that may need source modifications. Beyond that, I don't know anything.
> 
> build the app
 >>how then ?

**Comment by SparkingPlayer** [comment]
> 

How

**Comment by LittlePlanetCD** [comment]
> > 
> 
> How

you need to have a computer and Android Studio to compile it.

**Comment by Rubberduckycooly** [comment]
You get access to The encore DLC by building it yourself. We assume by doing this that you've bought the encore DLC on steam/switch/whatever, please don't pirate the game, buy sonic mania with money. Closing this since everyone's just repeating themselves.

**Comment by tedmakestuff** [comment]
> You get access to The encore DLC by building it yourself. We assume by doing this that you've bought the encore DLC on steam/switch/whatever, please don't pirate the game, buy sonic mania with money. Closing this since everyone's just repeating themselves.

awe, I don't have a Windows PC to compile it, not that I can run Sonic Mania anyways, but I do own the game & DLC on steam and switch.

**Comment by imagochan** [comment]
I've got a question, to use this decomp is sonic mania enough or do I really need to buy the encore dlc for the game? (steam), if I were to lack the DLC do I lose anything?

**Comment by MegAmi24** [comment]
> I've got a question, to use this decomp is sonic mania enough or do I really need to buy the encore dlc for the game? (steam), if I were to lack the DLC do I lose anything?

You can download builds from the Releases sections of [RSDKv5](https://github.com/RSDKModding/RSDKv5-Decompilation/releases/latest) and [Mania](https://github.com/RSDKModding/Sonic-Mania-Decompilation/releases/latest) and play the decomp that way. It'll work just fine aside from not being able to access the DLC content.

I want to note that [the DLC is currently on sale for about a dollar](https://store.steampowered.com/app/845640/Sonic_Mania__Encore_DLC/), so if you want to get it, now's the time.
