### ISSUE TITLE
Smal screen

### ISSUE THREAD

**Issue by Ieukejdehejn** [Rubberduckycooly/RSDKv5-Decompilation#260]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/14798670/log.txt)
Can you please fix my log.txt because it's an small screen please🙏

![Screenshot_20240227_121449](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/165348068/140eeb69-79d7-4dce-9cb4-121f974e7dcb)

**Comment by Ieukejdehejn** [comment]
Snapdragon 410

**Comment by Mefiresu** [comment]
This issue has been fixed for a while, please compile the game yourself to get the latest fixes.
