### ISSUE TITLE
Smal screen i have

### ISSUE THREAD

**Issue by Ieukejdehejn** [Rubberduckycooly/RSDKv5-Decompilation#261]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/14809683/log.txt)

 Hi can you please fix my log.txt because I have an small screen? 

![Screenshot_20240227_121449](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/assets/165348068/da9a5f06-1e45-4984-8ee4-b37378a432b1)

**Comment by Ieukejdehejn** [comment]
Snap Dragon 410

**Comment by MegAmi24** [comment]
Please stop opening duplicate issues. We have already made it clear that this bug report is invalid.

**Comment by Ieukejdehejn** [comment]
Yeah I open new one because the want is no comments

**Comment by Ieukejdehejn** [comment]
Can you please fixed my log txt?

**Comment by Mefiresu** [comment]
You got your answer in the previous issue you opened. https://github.com/Rubberduckycooly/RSDKv5-Decompilation/issues/260#issuecomment-2026750314
Please stop opening duplicate issues.
