### ISSUE TITLE
[Ubuntu] Audio isn't working

### ISSUE THREAD

**Issue by danilacasito** [Rubberduckycooly/RSDKv5-Decompilation#267]
So had Sonic 1 data.rsdk and built the RSDKv5 from source (because releases had a version which was linked to a library that isn't provided in Ubuntu 24.04 LTS) and CAN'T HEAR any audio but can play the game

**Comment by Mefiresu** [comment]
Origins datafiles don't have audio: https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/master/FAQ.md#q-why-is-there-no-audio
