### ISSUE TITLE
Enormous Issues with Mods,( sometimes replacing other sprites with mod sprites) [android]

### ISSUE THREAD

**Issue by Swapnekokitten** [Rubberduckycooly/RSDKv5-Decompilation#30]
This Bug, Consists of replacing sprites with other sprites that makes the game unplayable.

I tried the misfits pack, and some of the abilities/mechanics don’t work at all!

please fix this bug.

**Comment by jubbalub** [comment]
Hi, creator of misfits here. Code mods for the Steam version work in a completely different way than code mods for the decompilation. Thus, any Steam mod that changes code (unlock codes, custom abilities, etc) WILL NOT WORK for the decompilation. They will have to be completely rewritten.

**Comment by Swapnekokitten** [comment]
> Hi, creator of misfits here. Code mods for the Steam version work in a completely different way than code mods for the decompilation. Thus, any Steam mod that changes code (unlock codes, custom abilities, etc) WILL NOT WORK for the decompilation. They will have to be completely rewritten.

This explains why the sprites changed, just a question could you guys port it to the new decompilation?
