### ISSUE TITLE
Black screen with audio (many people reported) 

### ISSUE THREAD

**Issue by Yaseen117** [Rubberduckycooly/RSDKv5-Decompilation#32]
I have a huawei y9 2019 hisilicon kirin 710 the game runs with everything BUT without display i know its better to have a snapdragon but i want to play the game anywhere i have it on my pc so please post a fix or an update.

**Comment by tedmakestuff** [comment]
I tried on a Redmi 9, same thing.

**Comment by MGRich** [comment]
Duplicate of #8.
