### ISSUE TITLE
super sonic doesn't work 

### ISSUE THREAD

**Issue by deadluz** [Rubberduckycooly/RSDKv5-Decompilation#36]
i can't turn into super sonic even though i collect all the emeralds and 50 rings.

steps: In order to turn into him, you need to collect at least 50 rings. After that, just jump and hit the jump button again while in the air to morph into him. <- It does not work 

(android)

**Comment by breakthetargets** [comment]
not a bug, the super button isn't mapped.

**Comment by Rubberduckycooly** [comment]
will be added in a future update, not relevent to RSDKv5 since its a mod anyways.
