### ISSUE TITLE
[Linux] Music resumes playing when refocusing the game while in the dev menu

### ISSUE THREAD

**Issue by Longestboi** [Rubberduckycooly/RSDKv5-Decompilation#38]
While in the RSDKv5 dev menu, the background music of a scene will resume playing if you defocus and then refocus the window.

Tested on commit `d858b8`.
Distro this was encountered on is Ubuntu 21.10.

Not sure if the two points above matter, but specificity isn't bad.

**Comment by MGRich** [comment]
Actually an original issue as well, I believe. Could be GL3 though; I'll check and make sure.

**Comment by Rubberduckycooly** [comment]
fixed in 50398d7949f49b462cce2ef0887554700ecc737d, it was something I'd been meaning to get around to but just never did lol
