### ISSUE TITLE
Black screen persisting on Unisoc Tiger T310 (RP2+) after fix

### ISSUE THREAD

**Issue by ADHDefy** [Rubberduckycooly/RSDKv5-Decompilation#39]
**The Problem:**

When I launch the game from the shortcut, the screen is black, it plays the classic Sega logo sound, the sound of Sonic revving up, and then it crashes. The APK was built this morning (8/23), mod folder with GLS3 shaders mod was taken directly from the Discord and modified only to add a 4:3 aspect ratio mod (the problem persists with or without the 4:3 mod).

_EDIT: The same APK is confirmed working on Snapdragon and Mediatek devices._

**Hardware:**

- Retroid Pocket 2+
- Unisoc Quad-core Tiger T310
- 2 GB LPDDR4x RAM
- 480p Display

**Software:**

- Android 9

**My Mods Folder:**

![Screenshot_20220823](https://user-images.githubusercontent.com/105878544/186235413-085cb668-4707-4899-9c9e-8fafef4f70b3.png)

**Comment by breakthetargets** [comment]
Being worked on.

**Comment by david331534** [comment]
> **El problema:**
> 
> Cuando ejecuto el juego desde el acceso directo, la pantalla está en negro, reproduce el sonido clásico del logotipo de Sega, el sonido de Sonic acelerando y luego se cuelga. El APK se creó esta mañana (23/8), la carpeta de mods con el mod de sombreadores GLS3 ​​se tomó directamente de Discord y se modificó solo para agregar un mod de relación de aspecto 4:3 (el problema persiste con o sin el mod 4:3).
> 
> _EDITAR: Se confirma que el mismo APK funciona en dispositivos Snapdragon y Mediatek._
> 
> **Hardware:**
> 
> * Bolsillo retroide 2+
> * Unisoc de cuatro núcleos Tiger T310
> * 2 GB de memoria RAM LPDDR4x
> * Pantalla 480p
> 
> **Software:**
> 
> * androide 9
> 
> **Mi carpeta de mods:**
> 
> ![Captura de pantalla_20220823](https://user-images.githubusercontent.com/105878544/186235413-085cb668-4707-4899-9c9e-8fafef4f70b3.png)



> **El problema:**
> 
> Cuando ejecuta el juego desde el acceso directo, la pantalla está en negro, reproduce el sonido clásico del logotipo de Sega, el sonido de Sonic acelerando y luego se cuelga. El APK se creó esta mañana (23/8), la carpeta de mods con el mod de sombreadores GLS3 ​​​​se tomó directamente de Discord y se modificó solo para agregar un mod de relación de aspecto 4:3 (el problema persiste con o pecado el mod 4:3).
> 
> _EDITAR: Se confirma que el mismo APK funciona en dispositivos Snapdragon y Mediatek._
> 
> **Hardware:**
> 
> * Bolsillo retroide 2+
> * Unisoc de cuatro nucleos Tiger T310
> * 2 GB de memoria RAM LPDDR4x
> * Pantalla 480p
> 
> **Software:**
> 
> * androide 9
> 
> **Mi carpeta de mods:**
> 
> ![captura de pantalla_20220823](https://user-images.githubusercontent.com/105878544/186235413-085cb668-4707-4899-9c9e-8fafef4f70b3.png)

hey bro do you think you can pass me the link of the mods folder with the shaders mod? because I don't have Discord I would really appreciate it

**Comment by MGRich** [comment]
Duplicate of #8.

**Comment by david331534** [comment]
> Duplicado del #8 .

Hi how are you
