### ISSUE TITLE
The game's himself works but something's wrong on it or pretty not?

### ISSUE THREAD

**Issue by Cure643** [Rubberduckycooly/RSDKv5-Decompilation#43]
Alrighty, i was thinking to return with mania from an while this time with this release completely but eventually.... the game it is stuck though the white screen before it was already started there's the way to figure out fixing it or otherwise it literally happens from newest builds which it's stuck around at same time the white screen highly, just let me knew on it able to decide for once!
![RSDKv5U_x64_yzTntYx3pc](https://user-images.githubusercontent.com/69331852/186553919-b289038b-1970-4501-b735-01126e9b60a9.png)
and also, i'm using the windows builds so, if you might to forgot it.

**Comment by yehyasabry** [comment]
Can you give me the APK to test please

**Comment by Cure643** [comment]
> Can you give me the APK to test please

Nope, you must to do it yourself since it's possible to getting from android it's only the windows users on it that it would found the glitches.

**Comment by yehyasabry** [comment]
Me not nope you the nope because I can git if from rsdk website in GitHub but I want the new update so you talk about windows stop ahhh all here know the windows not have any thing and you the nope because you can fix this easy erors

**Comment by yehyasabry** [comment]
And I'm sorry for this so bye
