### ISSUE TITLE
[Android]smal screen error

### ISSUE THREAD

**Issue by Luccas7383** [Rubberduckycooly/RSDKv5-Decompilation#44]
can someone please explain to me why my game has the smal screen

![Screenshot_20220825-032837](https://user-images.githubusercontent.com/112060806/186591684-b2fb4d9d-3e26-42ba-b17d-cf0a3aa73e71.png)

**Comment by MGRich** [comment]
Pointing towards #8, but not counting as a duplicate: it's in the same vein.

**Comment by Luccas7383** [comment]
Snapdragon 410

**Comment by Luccas7383** [comment]
> What the CPU that you use

Snapdragon 410

**Comment by david331534** [comment]
> Pointing towards #8, but not counting as a duplicate: it's in the same vein.

Hello, do you have a version of android compatible with my Qualcomm snapdragon 400 cpu?

**Comment by Luccas7383** [comment]
> Apontando para #8 , mas não contando como duplicata: está na mesma linha.

a question do you have a forecast of when you will release a new version

**Comment by Luccas7383** [comment]
> Pointing towards #8, but not counting as a duplicate: it's in the same vein.

the question do you have a forecast of when you will release a new version

**Comment by Luccas7383** [comment]
> Apontando para #8 , mas não contando como duplicata: está na mesma linha.

**Comment by Luccas7383** [comment]
> Apontando para #8 , mas não contando como duplicata: está na mesma linha.

do you have a solution for this error

**Comment by Luccas7383** [comment]
> Pointing towards #8, but not counting as a duplicate: it's in the same vein.

do you have a solution for this error

**Comment by MGRich** [comment]
Please show what occurs when built with the latest commit b4504accc6d2a13d239c420f2194150a18957eb9.

**Comment by MGRich** [comment]
Fixed in 12cf4f897af292e94edbdc5dd480971457e9a503.
