### ISSUE TITLE
[Windows] Decomp sometimes continues to run in the background after closing it

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/RSDKv5-Decompilation#49]
Pretty much as the title says. Even the music continues to play. Don't really have a consistent way to get it to occur sadly.

**Comment by breakthetargets** [comment]
If the backend matters, this happens a good amount on the DX11 for me.

**Comment by leoclubs** [comment]
hasn't happened to me yet with either GL3 , DX9 and DX11 versions

**Comment by MGRich** [comment]
Cannot reproduce on Unix-like systems.

**Comment by MegAmi24** [comment]
This seems to happen if you try to replace a mod's logic file while the game is running with that mod enabled.

**Comment by breakthetargets** [comment]
> This seems to happen if you try to replace a mod's logic file while the game is running with that mod enabled.

It's not just that, I've been able to trigger it without trying to replace a mod with a newer version.

**Comment by MegAmi24** [comment]
Found out how to consistently get the bug to occur:
Alt-Tab out of the window and while it's inactive close the game from the taskbar. Tested on v5U DX9 Release x64

**Comment by Rubberduckycooly** [comment]
should be fixed in a145d69a853c616e03fd62a9c4eb89069ce53e9e, please confirm if so and either close the issue or tag me depending on if it's fixed or not

**Comment by MegAmi24** [comment]
Seems to be fixed, I'll reopen this issue if anything comes up again
