### ISSUE TITLE
Small screen error on Qualcomm snapdragon 400 cpu [Android]

### ISSUE THREAD

**Issue by david331534** [Rubberduckycooly/RSDKv5-Decompilation#51]
![Screenshot_2022-08-26-18-25-39](https://user-images.githubusercontent.com/111930784/187007341-0a8f0e7e-4c5b-46d5-ab1c-606e422c90df.png)

this happens in the release version and I already tried everything I have used the shaders as a mod and the error still persists.
I have this error since the first day they released their first version. ¿Does anyone know if there is a solution to this error?

And if possible, could you pass me a version that is compatible with my cpu?.

I would really appreciate it, thank you!

**Comment by MGRich** [comment]
Duplicate of #44.
