### ISSUE TITLE
Super Can't Do [Android]

### ISSUE THREAD

**Issue by rajonpatNewAccount** [Rubberduckycooly/RSDKv5-Decompilation#53]
Super on the android Is cannot be. but why? well, the pause button is near the super button and i havent figured out any alternative way to go super.

**Comment by rajonpatNewAccount** [comment]
fix this pls.

**Comment by yehyasabry** [comment]
Can I ask you q little question sonic mania still have black screen in mediatek CPU

**Comment by rajonpatNewAccount** [comment]
hm maybe its vsync thingy or somethin cuz it works fine for me

**Comment by LittlePlanetCD** [comment]
> hm maybe its vsync thingy or somethin cuz it works fine for me

it's not a vsync issue. it's a known bug with a variety of phones. it will be fixed.



> Super on the android Is cannot be. but why? well, the pause button is near the super button and i havent figured out any alternative way to go super.

There's no way to turn super on the android port yet, because the mod to give you touch controls is not finished.

Both of these issues, touch and the black screen, are already known and will be fixed eventually.

**Comment by Rubberduckycooly** [comment]
Super button will be in the next release, it's been completed it's just not ready yet.
