### ISSUE TITLE
[android] Tails cant carry no hedgehog.

### ISSUE THREAD

**Issue by rajonpatNewAccount** [Rubberduckycooly/RSDKv5-Decompilation#56]
Tails cant carry no hedgehog is referring to this bug in the decompilation of sonic mania in android where if you try to get carried by tails tails will drop you. Fix this please!

**Comment by c4scdev** [comment]
Just... look up and jump (twice). It's not that hard

**Comment by Rubberduckycooly** [comment]
Fixed already, it'll be in the next release
