### ISSUE TITLE
[SOLVED] [Linux] Can't build on Linux Mint 21 Cinnamon

### ISSUE THREAD

**Issue by SamuelTheTechnoKid** [Rubberduckycooly/RSDKv5-Decompilation#58]
I was going to run the prebuilt decomp version of Sonic Mania, installed every single thing needed, and it ran! But without the DLC? Come on, I have the DLC! I notice that you have to build for the DLC, but if I try that, EVEN AFTER INSTALLING DEPENDENCIES, this appears:
`make: *** [Makefile:224: bin/obj/Linux/GL3/RSDKv5/RSDKv5/main.o] Error 1`
And like a billion errors above that.
Could somebody help me, please?

**Comment by Longestboi** [comment]
You're probably going to have to give more information and all the errors if you want someone to help you out.
Can you paste all the output from make in a reply?

**Comment by SamuelTheTechnoKid** [comment]
> You're probably going to have to give more information and all the errors if you want someone to help you out.
> 
> Can you paste what command you ran? Can you paste all the output from make? What distro are you using?

-Just the make command. I also tried both with no sudo and with sudo.
-They're so much... I tried, but the list was VERY long! Take 2 more errors anyway:
```
./dependencies/all/tinyxml2/tinyxml2.h:12652:5: error: expected unqualified-id before ‘<’ token
12652 |     </style>
      |     ^
In file included from RSDKv5/main.cpp:1:
RSDKv5/RSDK/Core/RetroEngine.hpp: In function ‘void RSDK::RegisterGlobalVariables(void**, int32)’:
RSDKv5/RSDK/Core/RetroEngine.hpp:637:36: error: ‘DATASET_STG’ was not declared in this scope
  637 |     AllocateStorage(globals, size, DATASET_STG, true);
      |                                    ^~~~~~~~~~~

```
-Linux Mint 21, based in Ubuntu 22.04

**Comment by leoclubs** [comment]
i am on Linux Mint 21 Cinnamon (based on Ubuntu 22.04)
and i get the following error when i want to build
i could build mostly fine on Windows 10 but Win 10 has this weird lag for all games for me , running that same exact exe on Linux even with Wine/Proton has no lags , the Native Linux Build i got also has no lags so i wanted to be able to build here instead
![image](https://user-images.githubusercontent.com/104600382/187082075-360a4621-0321-4596-b995-236e1ffd9af5.png)

**Comment by santiagocezar** [comment]
> ```./dependencies/all/tinyxml2/tinyxml2.h:12652:5: error: expected unqualified-id before ‘<’ token
12652 |     </style>```

what the heck is that HTML style tag doing there???

you probably should clone the repository again with `git clone --recursive https://github.com/Rubberduckycooly/RSDKv5-Decompilation` and try compiling again

**Comment by santiagocezar** [comment]
> ```./dependencies/all/tinyxml2/tinyxml2.h:12652:5: error: expected unqualified-id before ‘<’ token
12652 |     </style>```

what the heck is that HTML style tag doing there???

you probably should clone the repository again with `git clone --recursive https://github.com/Rubberduckycooly/RSDKv5-Decompilation` and try compiling again

**Comment by SamuelTheTechnoKid** [comment]
> > ```
> > ./dependencies/all/tinyxml2/tinyxml2.h:12652:5: error: expected unqualified-id before ‘<’ token
> > 12652 |     </style>
> > ```
> 
> what the heck is that HTML style tag doing there???
> 
> you probably should clone the repository again with `git clone --recursive https://github.com/Rubberduckycooly/RSDKv5-Decompilation` and try compiling again

No idea why that appeared there. But I re-cloned it and it works now! One extra question: how do you build RSDKv5U instead of RSDKv5?

**Comment by MGRich** [comment]
Pass `RSDK_REVISION=3` to the `make` command.

**Comment by SamuelTheTechnoKid** [comment]
> Pass `RSDK_REVISION=3` to the `make` command.

Thank you!
