### ISSUE TITLE
[Linux] cannot build in Linux Mint

### ISSUE THREAD

**Issue by leoclubs** [Rubberduckycooly/RSDKv5-Decompilation#59]
i am on Linux Mint 21 Cinnamon
and i get the following error when i want to build
i could build mostly fine on Windows 10 but Win 10 has this weird lag for all games for me , running that same exact exe on Linux even with Wine/Proton has no lags , the Native Linux Build i got also has no lags so i wanted to be able to build here instead
![image](https://user-images.githubusercontent.com/104600382/187082075-360a4621-0321-4596-b995-236e1ffd9af5.png)

**Comment by SamuelTheTechnoKid** [comment]
Duplicate (#58), needs to be removed.

**Comment by leoclubs** [comment]
i was originally going to post under #58 but we're getting different errors i believe so there's no "need" to remove this

**Comment by leoclubs** [comment]
Update : came across a post in Sonic Mania Decompilation repo that mentioned cloning the git with recursive and using make STATIC=0 ... it successfully went through and i got a SonicMania.so

however i get the following error on RSDKv5 compiling now
![image](https://user-images.githubusercontent.com/104600382/187086528-28278a55-ca44-4141-a272-283a4b6ebfed.png)

it seems it does create an RSDKv5 binary file
![image](https://user-images.githubusercontent.com/104600382/187086562-4c6f8733-f741-4228-bd29-540ce1ad697d.png)
