### ISSUE TITLE
[Android] Press Garden Act 2 boss gets stuck

### ISSUE THREAD

**Issue by slambo311** [Rubberduckycooly/RSDKv5-Decompilation#62]
When I fought the Press Garden Act 2 Hard - boiled heavy, I the log was in the middle of the screen, and when I hit the hard boiled heavy, he went through the log. He then got stuck there. I could see a bit of the capsule, too.

**Comment by Longestboi** [comment]
This issue should probably be submitted to the [Sonic-Mania-Decompilation](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation) rather than this repo

**Comment by Rubberduckycooly** [comment]
Fixed as of https://github.com/Rubberduckycooly/RSDKv5-Example-Mods/commit/f2e373caaf335787dbe950a782ca4727744ed474
