### ISSUE TITLE
[All Platforms] Scene3D unoptimized?

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#63]
I was testing mods for Sonic Mania, and decided to boot up Mania Repainted.

I got to one of the special stages, and the game was chugging really hard due to the assets used in the scene, the image provided is SS1, where it lags the most.

![image](https://user-images.githubusercontent.com/24783625/187126450-6f91dc20-7be1-457d-982e-32877985103f.png)

I think this is a Scene3D issue, because this does not happen on Steam Sonic Mania. Seems to be just the RSDKv5 decomp acting up. Possibly needs optimization?

**Comment by Rubberduckycooly** [comment]
should be all fixed up in 7f23db18a46ba24e0e35f4c2feaf1aaed46b7fd9, re-open this if it's still lagging badly
