### ISSUE TITLE
black screen in sonic mania 

### ISSUE THREAD

**Issue by sUpersonic228** [Rubberduckycooly/RSDKv5-Decompilation#64]
![1661775406959](https://user-images.githubusercontent.com/112397316/187199479-02ccf419-9f2c-41f7-9fa5-d07327b116a0.jpg)

**Comment by Deltara3** [comment]
Known bug and this issue is a duplicate of another issue. Although may I have the full screenshot for logging purposes?

**Comment by sUpersonic228** [comment]
![Screenshot_20220829-192202](https://user-images.githubusercontent.com/112397316/187200318-6b1ac627-e906-4445-8d64-42ff1dbadc72.png)

**Comment by Deltara3** [comment]
Thanks, I shall mark this as not working in my spreadsheet.

**Comment by sUpersonic228** [comment]
Will this really be fixed?

**Comment by Deltara3** [comment]
Eventually. This spreadsheet I am referring to is for basically purely documentational purposes as I help with this issue quite frequently. If you're in the Discord, await an announcement in decomp-announcements.

**Comment by sUpersonic228** [comment]
where can i join the discord?
