### ISSUE TITLE
Sonic moon walks in special stages

### ISSUE THREAD

**Issue by santiagocezar** [Rubberduckycooly/RSDKv5-Decompilation#65]
Saw that you improved the sorting algorithm used in special stages, so I went to try it and Sonic turned into MJ:

![IMG_20220829_135840_188.png](https://user-images.githubusercontent.com/48573316/187254228-0f034da7-fb3a-42fc-91f7-968b35a9ac8e.png)

Might be a rendering issue?

**Comment by ActualMandM** [comment]
looks like the depth is inverted for 3d
![2022-08-29_12-37-02_RSDKv5U](https://user-images.githubusercontent.com/15317421/187283915-9462aa46-b0bb-48fc-b186-ba3412f3a49a.png)

**Comment by leoclubs** [comment]
![image](https://user-images.githubusercontent.com/104600382/187287035-24e60c3b-3c54-4114-b3e3-76a09507a7f6.png)
got the same issue here

**Comment by LittlePlanetCD** [comment]
same here

![image](https://user-images.githubusercontent.com/24783625/187306187-2af16b0b-8da2-44e2-a3c0-c4d4d9b7817e.png)

**Comment by Rubberduckycooly** [comment]
fixed in 47c0c6614f360de426e4b4bdf2ac727672535f8e
