### ISSUE TITLE
No Graphics, Sound and crashes 3 seconds after.

### ISSUE THREAD

**Issue by IOrbitSaturn** [Rubberduckycooly/RSDKv5-Decompilation#67]
I have a Samsung Galaxy Tab A7 Lite and it has a PowerVR Graphic Proccesor unit with OpenGL 3.4 i have heared that it is only compatible with SnapDragon's GPUs. Can make a update please?

**Comment by LittlePlanetCD** [comment]
It will be updated when it's ready, the android port is a work in progress, and this error will be fixed eventually

**Comment by IOrbitSaturn** [comment]
> It will be updated when it's ready, the android port is a work in progress, and this error will be fixed eventually

thanks, in windows it just appears a white screen
![Captura](https://user-images.githubusercontent.com/110071826/187317033-5ee4c6f9-91a9-4c8e-918d-ff9a0fb3fb9e.PNG)

i am doing well?, i used the Data.rsdk of Mania (Base Game) and nothing, i must put the Plus DLC?.

**Comment by LittlePlanetCD** [comment]
> > It will be updated when it's ready, the android port is a work in progress, and this error will be fixed eventually
> 
> thanks, in windows it just appears a white screen ![Captura](https://user-images.githubusercontent.com/110071826/187317033-5ee4c6f9-91a9-4c8e-918d-ff9a0fb3fb9e.PNG)
> 
> i am doing well?, i used the Data.rsdk of Mania (Base Game) and nothing, i must put the Plus DLC?.

you do not have the game.dll needed to boot sonic mania.

**Comment by IOrbitSaturn** [comment]
> > > Se actualizará cuando esté listo, el puerto de Android es un trabajo en progreso y este error se solucionará eventualmente.
> > 
> > 
> > gracias, en windows solo aparece una pantalla blanca![captura](https://user-images.githubusercontent.com/110071826/187317033-5ee4c6f9-91a9-4c8e-918d-ff9a0fb3fb9e.PNG)
> > me va bien?, use el Data.rsdk de Mania (Base Game) y nada, debo poner el Plus DLC?.
> 
> no tienes el game.dll necesario para iniciar sonic mania.

THANKS SO MUCH

**Comment by IOrbitSaturn** [comment]
> 

and btw where is it. i not see it on the actual Mania

**Comment by IOrbitSaturn** [comment]
> > 
> 
> and btw where is it. i not see it on the actual Mania

forget it i found it

**Comment by xcom169** [comment]
Hello All!

Sorry, but where is this game.dll ?
