### ISSUE TITLE
[All Platforms] Scene3D needs slight fixing.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#69]
It seems like the models polygons or tri's are not exactly rendering correctly. 

It was more noticable with mods like Mania repainted, but when using base mania, it's still obvious on most objects.

this is a picture of Sonic, on the decomp. notice how his hand is just slightly weird.

![image](https://user-images.githubusercontent.com/24783625/187334192-b1d38237-19a1-407d-8d31-f6ec18c40ed9.png)

Here's the same frame and character placement, but on Sonic Mania on Steam. Notice how it doesn't have the oddity on Sonic's hand.

![image](https://user-images.githubusercontent.com/24783625/187334303-a61f1bac-5418-48eb-9d10-b02f17837f7b.png)

This kind of "Polygon/Tri" issue is a lot more visible if you use a mod like Mania repainted.

I may post example screenshots of those later, but it was very obvious on the homers.

**Comment by LittlePlanetCD** [comment]
For a more, obvious comparison, I will be also using Mania Repainted.

the shoes of some of the homers usually look like this.

![image](https://user-images.githubusercontent.com/24783625/187349042-91d12d4e-16a8-489f-98f3-083f10a3f01a.png)

but look like this on the decomp.

![image](https://user-images.githubusercontent.com/24783625/187349100-d4d79134-156b-4b5d-9953-95df71eaace7.png)

there's also the more obvious polygon sort (?) on the sides of the homers, which usually looked like this on steam (and before the scene3d changes):

![image](https://user-images.githubusercontent.com/24783625/187349256-652940f9-2c19-4de2-84b3-b6fe29a49fd0.png)

but now, after all the changes, it looks like this when it shouldn't.

![image](https://user-images.githubusercontent.com/24783625/187349270-7f54574f-c2f1-48ad-9524-bd5a8a2814a9.png)

**Comment by Clownacy** [comment]
It turns out that 2040219d981a79fcdd2d833c44bd570e5e7f5edc only fixes some of the rendering issues described in this issue (Sonic, and a few issues with the Homers). 428eda461c45beddbb9b2af55ddee5979b7f1074 fixes the rest of them.
