### ISSUE TITLE
(Android) The game is not shown

### ISSUE THREAD

**Issue by fadeinside** [Rubberduckycooly/RSDKv5-Decompilation#7]
Original issue: [https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/37](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation/issues/37)

The game starts and is fully functional, the sound and controls are working, however, the game is just not shown. The log is available at the link above

**Comment by macadoodoo** [comment]
Same problem, have you found a way to fix it yet?

**Comment by fadeinside** [comment]
> Same problem, have you found a way to fix it yet?

This happens on non-Snapdragon chipsets. It's worth waiting for a fix from the development team.

**Comment by macadoodoo** [comment]
Alright.

**Comment by Fancy2209** [comment]
If it helps this is my CPU
![Screenshot_20220817-155939-2.png](https://user-images.githubusercontent.com/64917206/185187562-98a6aced-ffb5-47b8-8a8b-e45548c00d53.png)

**Comment by yehyasabry** [comment]
Hi all I have the same problem my mobile is Infinix work with mediatek CPU so I want to fix this problem any one here know how to fix

**Comment by c4scdev** [comment]
I have two MediaTek phones and RSDKv5 (Sonic Mania) works fine. (MT6763V/MT6750) No visuals/video output though

**Comment by yehyasabry** [comment]
Hi I have mediatek mts6739 when I open sonic mania sound only with black screen

**Comment by yehyasabry** [comment]
![github](https://user-images.githubusercontent.com/107801712/185307485-7128c5b5-6f42-4332-b8bb-cd262a1d7ba7.png)

**Comment by fadeinside** [comment]
Fixed in recent commits. The issue is closed
