### ISSUE TITLE
[Linux, v5] Goop in Chemical Plant disappears after reaching certain height

### ISSUE THREAD

**Issue by grindersky** [Rubberduckycooly/RSDKv5-Decompilation#76]
only happens in v5, checked v5U and this doesn't happen in that version of the executable.
https://user-images.githubusercontent.com/31354929/188248004-1c948bb9-b26e-4630-ae6d-180d52f39fb8.mp4

**Comment by grindersky** [comment]
actually, this also happens to all the goops in Chemical Plant Act 2 as well

https://user-images.githubusercontent.com/31354929/188282971-bbc087ab-aea8-4ebd-b9ee-fce4af4043b4.mp4

**Comment by stxticOVFL** [comment]
No leads... if anything pops up, feel free to re-open.

**Comment by grindersky** [comment]
> No leads... if anything pops up, feel free to re-open.

I'll mention that it only happens with the velocity mod (and PLEASE help me build that piece of crap GameAPI is broken for me or something)
