### ISSUE TITLE
(V5 (and V5U ?)) Incorrect Dev Menu stats position

### ISSUE THREAD

**Issue by LittlePlanetCD** [Rubberduckycooly/RSDKv5-Decompilation#77]
Left is Decomp, right is Sonic Mania Steam

![image](https://user-images.githubusercontent.com/24783625/188251657-ea071620-cfb9-4fb7-b358-f4670c0de44b.png)

**Comment by Rubberduckycooly** [comment]
should be fixed in c1dca90e70936c34893b49836cc7bc2673c17bcf
