### ISSUE TITLE
[Android] No visuals, crashes at title screen

### ISSUE THREAD

**Issue by CebolaBros64** [Rubberduckycooly/RSDKv5-Decompilation#8]
[log.txt](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/files/9351375/log.txt)

Screen is completelly black; SEGA jingle plays, game crashes a little after the title screen theme starts playing.

**Comment by MGRich** [comment]
This is as far as GPU specific; some GPUs break and others don't. I'll update this in a little bit to mark what 
GPUs do and don't.

**Comment by MGRich** [comment]
**Known working:**
- Snapdragon CPUs
- Mediatek Helio

Known **NOT** working:
- Mali
- Exynos

**Comment by yehyasabry** [comment]
Thank you can you give me the APK

**Comment by yehyasabry** [comment]
Sorry where the apk

**Comment by yehyasabry** [comment]
Hi MGRich  can you tell me the vertion that work with the mediatek CPU

**Comment by NotFlawffles** [comment]
> **Known working:**
> 
>     * Snapdragon CPUs
> 
>     * Mediatek Helio
> 
> 
> Known **NOT** working:
> 
>     * Mali
> 
>     * Exynos
> 
>     * Unisocs
> 
>     * Cortex

Hey, you referenced Mediatek Helio in known working, I'm on Mediatek Helio G88 and i still have the same issue, a black screen with only audio, and then crushes at menu screen

**Comment by refused9496** [comment]
> > **Known working:**
> > ```
> > * Snapdragon CPUs
> > 
> > * Mediatek Helio
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Known **NOT** working:
> > ```
> > * Mali
> > 
> > * Exynos
> > 
> > * Unisocs
> > 
> > * Cortex
> > ```
> 
> Hey, you referenced Mediatek Helio in known working, I'm on Mediatek Helio G88 and i still have the same issue, a black screen with only audio

same, except mine is G35

**Comment by MGRich** [comment]
Please build and test this latest commit.

**Comment by milesthecreator** [comment]
Can confirm the latest commit fixed it for me!
![Screenshot_20221116-204527_Sonic Mania](https://user-images.githubusercontent.com/45196539/202382972-5005fc73-36a5-4b1c-a8e6-7a7d838d3738.png)

**Comment by MGRich** [comment]
Formally fixed as of 12cf4f897af292e94edbdc5dd480971457e9a503.

**Comment by raphaelko62** [comment]
it seems that on newer versions, exynos 9810 has this issue. if there was a way to download the exact version in which this got fixed, i would be very grateful. for further reference, my phone is a samsung galaxy s9+ with 6 gigabytes of ram and 64 gigabytes of storage. thank you for your help.
