### ISSUE TITLE
Support loading an upacked RSDK

### ISSUE THREAD

**Issue by MystiK791** [Rubberduckycooly/RSDKv5-Decompilation#81]
Adding support for loading assets from an unpacked RSDK would likely speed up loading times on platforms such as the 3DS and PS Vita. Not needing to have to decompress files would hopefully make up for those systems' slower storage.

**Comment by MegAmi24** [comment]
There's already support for that, just put the files in a folder called Data

**Comment by MystiK791** [comment]
Ok then! Thanks!

(Also, is there any place to find instructions on how to compile the 3DS version? I can't even find any references to the 3DS by studying the makefile)

**Comment by MegAmi24** [comment]
The master branch doesn't maintain the 3DS port, [this fork](https://github.com/SaturnSH2x2/RSDKv5-Decompilation) is what you're looking for

**Comment by MystiK791** [comment]
I'm aware, but it has issues off and I can't find any way to build the repo anywhere.

**Comment by MystiK791** [comment]
Should I try submitting a dummy PR or something?

**Comment by MystiK791** [comment]
Sorry for dragging this out... can you point me towards the file that loads the RASK folder?
