### ISSUE TITLE
Can't load  Sonic 3u.rdsk

### ISSUE THREAD

**Issue by Asus769** [Rubberduckycooly/RSDKv5-Decompilation#86]
When loading it will just freeze up

**Comment by SCOTT0852** [comment]
The Origins version of Sonic 3 is RSDK v5. v5 requires the game to be decompiled as well (which is why Mania needs a "game.dll" while v3 and v4 data files don't). There are no plans to decompile Origins S3.

**Comment by Asus769** [comment]
ok
