### ISSUE TITLE
[Suggestion] Android workflow job

### ISSUE THREAD

**Issue by slambo311** [Rubberduckycooly/RSDKv5-Decompilation#88]
Considering you did it for v3 and v4, I feel like the workflow should build the android version too.

**Comment by MGRich** [comment]
We opted out of adding Android as it not only takes too long (so it drains at our free Github CI minutes) but it's also quite big because 85 essentially compiles the executable 4 times (thus wasting our free Github CI space.)

**Comment by slambo311** [comment]
Alright. In that case, when's the next release?

**Comment by MGRich** [comment]
No ETA. People have already shared non-Plus builds in REMS.
