### ISSUE TITLE
C++11 Support

### ISSUE THREAD

**Issue by DanTheMan827** [Rubberduckycooly/RSDKv5-Decompilation#94]
Given that the only thing keeping the engine from compiling with C++11 is `filesystem`, perhaps it would be possible to replace it with either C++11 code or gulrak file system instead?

I’ve successfully compiled with this in C++11 standards mode for an older ARM Linux system

https://github.com/gulrak/filesystem

**Comment by MGRich** [comment]
`std::filesystem` is only required when using the mod loader, so I won't add an extra dependency for it. However, this is a very good resource for ports, so I will pin this issue. Thank you!
