### ISSUE TITLE
[Linux, v5] Can't clip through ground like in the Steam version of Sonic Mania

### ISSUE THREAD

**Issue by grindersky** [Rubberduckycooly/RSDKv5-Decompilation#95]
https://user-images.githubusercontent.com/31354929/189067810-c46d9b39-f71b-48de-8da4-fd58018a1577.mp4

unlike in the Steam version of Sonic Mania, in the decomp the floor just spits me out frame after "clipping" through it.

it should look like this: 
![fsdfsdsdfgfsd](https://user-images.githubusercontent.com/31354929/189068217-a0dec98d-eb82-47c1-90fb-46ed84ab9073.png)

tutorial on how to do it (it's basically the same way as clipping through a wall): https://youtu.be/QbWz7ZQdnVs?t=756

**Comment by stxticOVFL** [comment]
Ended up being a user error.
