### ISSUE TITLE
What are the differences between v5 and v5U?

### ISSUE THREAD

**Issue by b-0-x-3-d** [Rubberduckycooly/RSDKv5-Decompilation#98]
I've been wondering which one to use.

**Comment by leoclubs** [comment]
5U because it is [Ultimate]

**Comment by b-0-x-3-d** [comment]
I meant like, are there specific differences? Like does one have better something?

**Comment by RinMaru** [comment]
i too was curious about this

**Comment by MGRich** [comment]
v5 alone is what's used in Mania.
v5U, known as v5 Ultimate, is cross. compatible between v3 and v4 (with slight updates to the two,) and has tweaked collision and more exposed collision and anitile functions. This is used in Origins.
